import type { ReferenceDeck } from "@/data/types";

/**
 * Every mechanism from the carbonyl trainer, as one card each.
 *
 * Generated by scripts/make_flashcards.py in the mechanism_trainer repo, which
 * reads the reaction data and the map and stitches the structure drawings into
 * one scheme per card. Do not hand edit: the next run overwrites it, and the
 * point of generating it is that a card cannot drift from the reaction page it
 * came from.
 *
 * The front of the card is the starting material and the reagents, with the
 * conditions and whether it is reversible printed underneath. The back is the
 * product. Quiz mode blurs the badge and crops the right hand side of the
 * scheme, which is where the product is drawn, so one picture serves both sides.
 *
 * Sorted by what the reaction primarily is rather than by which file it came
 * from, and each reaction appears exactly once. Several could sit under two
 * headings, and choosing one on purpose matters: a card in two piles is a card
 * you think you know because you met it in the other one.
 */
export const carbonylsDeck: ReferenceDeck = {
  kind: "reference",
  id: "carbonyls",
  title: "Carbonyls",
  short: "Carbonyls",
  // Lives under Organic Chemistry II > Lab, in its own folder alongside the
  // LCTA and the reference sheets.
  group: "carbonyls",
  titleLines: ["CARBONYL", "REACTIONS"],
  subtitle:
    "Every mechanism from the trainer, one card each. Reactants and reagents on the front, product on the back, with the conditions on every card.",
  blurb:
    "Thirty carbonyl reactions with their reagents, conditions and products. Grouped by what the reaction actually is, so the ones that share a mechanism sit together.",
  about:
    "One card per mechanism, drawn from the same data as the trainer itself.\n\nEvery card carries three things beyond the reaction: whether it runs in acid, base, neutral or anhydrous conditions, whether it is reversible, and the temperature when that is the answer to the question. Those three decide more exam questions than the arrows do.\n\nGrouped by what the reaction primarily is. Nucleophilic addition and nucleophilic acyl substitution are the same first step and differ only in whether anything can leave, so they sit next to each other on purpose.",
  footNote:
    "If nothing on the carbon can leave, the nucleophile stays. If something can, it goes.",
  motif: "attack",
  from: "#4338ca",
  to: "#c026d3",
  preview: {
    width: 420,
    height: 168,
    // The product is drawn in the right hand third, so cropping it is what makes
    // the same picture work as both sides of the card.
    cropRight: "37%",
  },
  groups: [
    {
      heading: "Nucleophilic addition — Aldehydes and ketones. Nothing on the carbon can leave, so whatever adds stays.",
      items: [
        { title: "NaBH₄ on a ketone", description: "Acetophenone  +  NaBH₄ , MeOH   ·   neutral  ·  irreversible  ·  0 °C to room temperature", badge: "1-Phenylethanol", image: "carbonyl_nabh4-ketone.svg" },
        { title: "Cyanohydrin formation", description: "Acetone  +  NaCN , H₂O, pH ≈ 10   ·   basic  ·  irreversible  ·  Room temperature", badge: "Acetone cyanohydrin", image: "carbonyl_cyanohydrin.svg" },
        { title: "Acetylide addition to a ketone", description: "Acetone  +  HC≡CH, NaNH₂ , NH₃ (l); then H₃O⁺   ·   basic  ·  irreversible  ·  −33 °C in liquid ammonia, then acidic workup", badge: "2-Methyl-3-butyn-2-ol", image: "carbonyl_acetylide.svg" },
        { title: "Carboxylic acid from a Grignard and CO₂", description: "Carbon dioxide  +  CH₃MgBr , then H₃O⁺   ·   anhydrous  ·  irreversible  ·  Dry ice, then warm", badge: "Acetic acid", image: "carbonyl_grignard-co2.svg" },
        { title: "Wittig olefination", description: "Benzaldehyde  +  Ph₃P=CH₂ , THF   ·   anhydrous  ·  irreversible  ·  0 °C to room temperature", badge: "Styrene", image: "carbonyl_wittig.svg" },
        { title: "Cyclic hemiacetal", description: "5-hydroxypentanal  +  H⁺ cat. , (intramolecular)   ·   acidic  ·  reversible  ·  Room temperature", badge: "Cyclic hemiacetal", image: "carbonyl_cyclic-hemiacetal.svg" },
      ],
    },
    {
      heading: "Nucleophilic acyl substitution — A derivative, so the oxygen comes back down and pushes a leaving group out.",
      items: [
        { title: "Acetylation of vanillin", description: "Vanillin  +  Ac₂O , NaOH , H₂O   ·   basic  ·  irreversible  ·  Room temperature", badge: "Vanillin acetate", image: "carbonyl_vanillin-acetylation.svg" },
        { title: "Anhydride from an acid chloride", description: "Acetyl chloride  +  CH₃CO₂⁻ , pyridine   ·   neutral  ·  irreversible  ·  Room temperature", badge: "Acetic anhydride", image: "carbonyl_anhydride.svg" },
        { title: "Gilman reagent on an acid chloride", description: "Benzoyl chloride  +  Me₂CuLi , Et₂O, −78 °C   ·   anhydrous  ·  irreversible  ·  −78 °C", badge: "Acetophenone", image: "carbonyl_gilman.svg" },
        { title: "Nitrile hydrolysis, basic", description: "Benzonitrile  +  NaOH, H₂O , heat   ·   basic  ·  irreversible  ·  Reflux", badge: "Benzoate", image: "carbonyl_nitrile-basic.svg" },
        { title: "Nitrile hydrolysis, acidic", description: "Benzonitrile  +  H₃O⁺ , heat   ·   acidic  ·  irreversible  ·  Reflux, often for hours", badge: "Benzoic acid", image: "carbonyl_nitrile-acidic.svg" },
      ],
    },
    {
      heading: "Reduction — Hydride in, or the C=O taken off the molecule altogether.",
      items: [
        { title: "LiAlH₄ on an ester", description: "Methyl benzoate  +  LiAlH₄ (excess) , Et₂O; then H₃O⁺   ·   anhydrous  ·  irreversible  ·  0 °C to room temperature, then acidic workup", badge: "Benzyl alcohol", image: "carbonyl_lialh4-ester.svg" },
        { title: "DIBAL-H on an ester", description: "Methyl benzoate  +  DIBAL-H (1 eq) , toluene, −78 °C; then H₃O⁺   ·   anhydrous  ·  irreversible  ·  −78 °C, then acidic workup", badge: "Benzaldehyde", image: "carbonyl_dibal.svg" },
        { title: "Wolff–Kishner reduction", description: "Acetophenone  +  H₂NNH₂ , KOH , diethylene glycol, Δ   ·   basic  ·  irreversible  ·  180–200 °C in a high-boiling solvent", badge: "Ethylbenzene", image: "carbonyl_wolff-kishner.svg" },
        { title: "Clemmensen reduction", description: "Acetophenone  +  Zn(Hg) , conc. HCl, Δ   ·   acidic  ·  irreversible  ·  Reflux in concentrated HCl", badge: "Ethylbenzene", image: "carbonyl_clemmensen.svg" },
      ],
    },
    {
      heading: "Reactions of the acids — A carboxylic acid is a poor electrophile. Each of these is a way around that.",
      items: [
        { title: "Fischer esterification", description: "Benzoic acid  +  CH₃OH , H₂SO₄ cat.   ·   acidic  ·  reversible  ·  Reflux", badge: "Methyl benzoate", image: "carbonyl_fischer.svg" },
        { title: "Acid chloride from a carboxylic acid", description: "Benzoic acid  +  SOCl₂ , pyridine   ·   anhydrous  ·  irreversible  ·  Room temperature, sometimes warmed", badge: "Benzoyl chloride", image: "carbonyl_socl2.svg" },
        { title: "Decarboxylation of a β-keto acid", description: "Acetoacetic acid  +  Δ   ·   neutral  ·  irreversible  ·  Heat, around 150 °C", badge: "Acetone", image: "carbonyl_decarboxylation.svg" },
      ],
    },
    {
      heading: "Oxidation — Alcohol up to a carbonyl. How far it goes is the whole question.",
      items: [
        { title: "PCC oxidation of a primary alcohol", description: "Benzyl alcohol  +  PCC , CH₂Cl₂, anhydrous   ·   anhydrous  ·  irreversible  ·  Room temperature", badge: "Benzaldehyde", image: "carbonyl_pcc.svg" },
        { title: "Jones oxidation of a secondary alcohol", description: "Propan-2-ol  +  CrO₃, H₂SO₄ , H₂O, acetone   ·   acidic  ·  irreversible  ·  0 °C to room temperature", badge: "Acetone", image: "carbonyl_jones.svg" },
        { title: "Jones oxidation of a primary alcohol", description: "Benzyl alcohol  +  CrO₃, H₂SO₄ , H₂O, acetone   ·   acidic  ·  irreversible  ·  0 °C to room temperature", badge: "Benzoic acid", image: "carbonyl_jones-primary.svg" },
      ],
    },
    {
      heading: "Acid and base catalysis: acetals, imines, enamines — All reversible, all acid catalysed, and all the same first four steps.",
      items: [
        { title: "Protecting a ketone as an acetal", description: "Acetophenone  +  HOCH₂CH₂OH , TsOH cat. , benzene, −H₂O (Dean–Stark)   ·   acidic  ·  reversible  ·  Reflux, with water removed", badge: "Cyclic acetal", image: "carbonyl_acetal-on.svg" },
        { title: "Removing an acetal", description: "Cyclic acetal  +  H₃O⁺ , excess H₂O   ·   acidic  ·  reversible  ·  Room temperature, aqueous", badge: "Acetophenone", image: "carbonyl_acetal-off.svg" },
        { title: "Protecting a ketone as a dimethyl ketal", description: "Acetophenone  +  2 CH₃OH , H⁺ cat., −H₂O   ·   acidic  ·  reversible  ·  Reflux, water removed", badge: "Dimethyl ketal", image: "carbonyl_acetal-ome.svg" },
        { title: "Imine from an aldehyde and a primary amine", description: "Benzaldehyde  +  CH₃NH₂ , H⁺ cat., pH 4-5   ·   acidic  ·  reversible  ·  Room temperature", badge: "N-methylbenzaldimine", image: "carbonyl_imine.svg" },
        { title: "Enamine from a symmetric ketone", description: "Cyclohexanone  +  pyrrolidine , H⁺ cat., −H₂O   ·   acidic  ·  reversible  ·  Reflux, water removed", badge: "1-pyrrolidinocyclohexene", image: "carbonyl_enamine-sym.svg" },
        { title: "Enamine from an asymmetric ketone", description: "2-methylcyclohexanone  +  pyrrolidine , H⁺ cat., −H₂O   ·   acidic  ·  reversible  ·  Reflux, water removed", badge: "Less substituted enamine", image: "carbonyl_enamine-asym.svg" },
        { title: "Alkylation of an enamine", description: "1-pyrrolidinocyclohexene  +  CH₃I , then H₂O   ·   neutral  ·  irreversible  ·  Room temperature, then aqueous workup", badge: "2-methylcyclohexanone", image: "carbonyl_enamine-alkylation.svg" },
      ],
    },
    {
      heading: "Making the reagents — Two things the reactions above assume you already have.",
      items: [
        { title: "Friedel-Crafts acylation", description: "Benzene  +  CH₃COCl , AlCl₃   ·   anhydrous  ·  irreversible  ·  0 °C to room temperature", badge: "Acetophenone", image: "carbonyl_friedel-crafts.svg" },
        { title: "Making a phosphonium ylide", description: "Triphenylphosphine  +  CH₃Br , then n-BuLi   ·   anhydrous  ·  irreversible  ·  0 °C, under nitrogen", badge: "Methylenetriphenylphosphorane", image: "carbonyl_ylide.svg" },
      ],
    },
  ],
};
