/**
 * How hard a pathway node is, MEASURED off the content it launches.
 *
 * WHY THIS FILE EXISTS. The sheet used to fill its pips from a table keyed by
 * node kind: spine 2, branch 2, gate 3, boss 4. Every spine and branch node in
 * the product therefore showed the same two pips, which is the chip's own kind
 * restated as a number. CLAUDE.md's rule is that anything shown to a student is
 * derived from data and never asserted, and a difficulty row that ranks nothing
 * is an assertion with dots on it.
 *
 * THE RULE, and it is the only one:
 *
 *   A MOVE is one thing the node's content grades. Difficulty is how many
 *   moves the node asks for, banded into the four pips.
 *
 *     a mechanism arrow                  1 move   (chem-core grades arrow by arrow)
 *     a fork choice inside a sequence    1 move
 *     a resonance arrow                  1 move
 *     any other authored beat            1 move   (one MCQ set, one match board,
 *                                                  one ladder, one synthesis gap
 *                                                  set: each is one graded surface)
 *
 *   A node whose lesson plan is empty has no content behind it, so it has NO
 *   difficulty and the sheet draws no pips. Absent is not "average".
 *
 * WHY A TABLE AND NOT A CALL. Counting arrows means importing the trainer
 * corpus, and app/courseUniverse.generated.ts already records what that costs:
 * "importing the corpus there put the whole authored curriculum in front of
 * every student". The pathway tab is entry-chunk code, so the measurement is
 * committed here as numbers and test/nodeDifficulty.test.ts RECOMPUTES it from
 * the real content on every run and fails if the two drift. The table is
 * evidence, not authorship: nobody chooses a row, the test regenerates it.
 */

/** Four pips, the same row the sheet draws. See PIP_COUNT in nodeSheetModel.ts. */
export type Pips = 1 | 2 | 3 | 4;

/**
 * Moves per node, regenerated by test/nodeDifficulty.test.ts. Sorted by node
 * id so a regeneration produces a readable diff. A node absent from this table
 * has no authored content and gets no pips.
 */
export const NODE_MOVES: Readonly<Record<string, number>> = Object.freeze({
  "u1-12v14": 5,
  "u1-allylic": 1,
  "u1-da": 3,
  "u1-ied": 1,
  "u1-kvt": 1,
  "u1-nbs": 1,
  "u1-x2": 3,
  "u10-acyl-protect": 6,
  "u10-amide-red": 2,
  "u10-basicity": 1,
  "u10-diazo-sub": 2,
  "u10-diazonium": 2,
  "u10-nitrile-red": 2,
  "u10-nitro-red": 1,
  "u10-red-amination": 2,
  "u11-acidity": 1,
  "u11-phenoxide": 2,
  "u14-orthogonal": 1,
  "u3-arenium": 4,
  "u3-blocking": 1,
  "u3-c-to-ch2": 2,
  "u3-directing": 1,
  "u3-fc-acyl": 4,
  "u3-halo": 4,
  "u3-nitration": 4,
  "u3-nitro-red": 1,
  "u3-sequencing": 3,
  "u3-sulfo": 4,
  "u4-lg-order": 8,
  "u4-meisenheimer": 8,
  "u4-snar": 8,
  "u5-anti-diol": 2,
  "u5-dehydration": 3,
  "u5-ep-acid": 2,
  "u5-ep-base": 2,
  "u5-epoxidation": 4,
  "u5-oxidation": 1,
  "u5-protecting": 1,
  "u5-roh-rx": 4,
  "u5-syn-diol": 1,
  "u5-tosylate": 4,
  "u5-williamson": 2,
  "u6-ir": 1,
  "u7-12v14": 2,
  "u7-acetal": 4,
  "u7-cyanohydrin": 2,
  "u7-enamine": 2,
  "u7-grignard": 2,
  "u7-hydration": 4,
  "u7-hydride": 2,
  "u7-imine": 2,
  "u7-mechanism": 2,
  "u7-protect": 1,
  "u7-to-ch2": 2,
  "u7-wittig": 4,
  "u8-acylcl-all": 4,
  "u8-amide-hyd": 6,
  "u8-anhydride": 6,
  "u8-decarb": 4,
  "u8-dibal": 2,
  "u8-fischer": 6,
  "u8-gilman": 4,
  "u8-hydrolysis": 6,
  "u8-ladder": 1,
  "u8-lialh4": 6,
  "u8-nitrile": 2,
  "u8-organomet": 6,
  "u8-tetrahedral": 4,
  "u8-to-acylcl": 6,
  "u8-to-anhydride": 4,
  "u8-transester": 4,
  "u9-acetoacetic": 4,
  "u9-aldol": 6,
  "u9-aldol-cond": 6,
  "u9-alkylation": 3,
  "u9-claisen": 5,
  "u9-crossed": 5,
  "u9-crossed-claisen": 5,
  "u9-cuprate": 7,
  "u9-dieckmann": 4,
  "u9-enolate-res": 6,
  "u9-halo-acid": 5,
  "u9-halo-base": 3,
  "u9-intra": 3,
  "u9-kvt-enolate": 1,
  "u9-malonic": 4,
  "u9-michael": 4,
  "u9-pka": 2,
  "u9-retro": 1,
  "u9-robinson": 9,
  "u9-tautomer": 5,
});

/**
 * The bands. Four pips over a range that runs from a single arrow to a full
 * multi-step sequence, so the cuts are where the work changes character: one
 * or two moves is a single idea, three or four is a short mechanism, five to
 * seven is a mechanism with a decision in it, and eight or more is a sequence.
 */
export function pipsForMoves(moves: number): Pips {
  if (moves <= 2) return 1;
  if (moves <= 4) return 2;
  if (moves <= 7) return 3;
  return 4;
}

/** The node's difficulty in pips, or null when nothing is authored behind it. */
export function difficultyForNode(nodeId: string): Pips | null {
  const moves = NODE_MOVES[nodeId];
  return moves === undefined || moves <= 0 ? null : pipsForMoves(moves);
}
