// GENERATED by scripts/build_card_distractors.py. Do not edit by hand.
// The wrong options for the Cards run's predict step: each has exactly the
// answer's element set and carbon count, derived with RDKit (see the script).

export interface PredictDistractor {
  /** Canonical SMILES. Data for tests; never shown to a student. */
  readonly smiles: string;
  /** RDKit's formula of the same structure. */
  readonly formula: string;
  /** What this structure is relative to the answer, shown after the pick. */
  readonly caption: string;
  readonly kind: string;
  /** "derived", or the registry reaction whose product this is. */
  readonly source: string;
  readonly light?: string;
  readonly dark?: string;
}

export const PREDICT_DISTRACTORS: Readonly<Record<string, readonly PredictDistractor[]>> = {
  "acetal-protection": [
    {
      "smiles": "CC#CC(O)c1ccccc1",
      "formula": "C10H10O",
      "caption": "What Acetylide addition to an aldehyde gives",
      "kind": "registry",
      "source": "acetylide-addition",
      "light": "cards/predict/a26bb2613659-light.svg",
      "dark": "cards/predict/a26bb2613659-dark.svg"
    },
    {
      "smiles": "O=C1C=C2CCCCC2CC1",
      "formula": "C10H14O",
      "caption": "What Robinson annulation gives",
      "kind": "registry",
      "source": "robinson-annulation",
      "light": "cards/predict/043bf829dd01-light.svg",
      "dark": "cards/predict/043bf829dd01-dark.svg"
    }
  ],
  "acetylide-addition": [
    {
      "smiles": "CC=CC(O)c1ccccc1",
      "formula": "C10H12O",
      "caption": "One reduction too far",
      "kind": "reduced",
      "source": "derived",
      "light": "cards/predict/ceee7550c8e8-light.svg",
      "dark": "cards/predict/ceee7550c8e8-dark.svg"
    },
    {
      "smiles": "CC#CCc1ccc(O)cc1",
      "formula": "C10H10O",
      "caption": "The same group on a different carbon",
      "kind": "regio",
      "source": "derived",
      "light": "cards/predict/4b68f6726c66-light.svg",
      "dark": "cards/predict/4b68f6726c66-dark.svg"
    }
  ],
  "acidchloride-to-amide": [
    {
      "smiles": "CNc1ccc(C=O)cc1",
      "formula": "C8H9NO",
      "caption": "The same group on a different carbon",
      "kind": "regio",
      "source": "derived",
      "light": "cards/predict/c116c621f9e7-light.svg",
      "dark": "cards/predict/c116c621f9e7-dark.svg"
    },
    {
      "smiles": "N#CC(O)c1ccccc1",
      "formula": "C8H7NO",
      "caption": "What Cyanohydrin formation gives",
      "kind": "registry",
      "source": "cyanohydrin",
      "light": "cards/predict/6798f0292753-light.svg",
      "dark": "cards/predict/6798f0292753-dark.svg"
    }
  ],
  "alcohol-dehydration": [
    {
      "smiles": "CC(C)C",
      "formula": "C4H10",
      "caption": "One reduction too far",
      "kind": "reduced",
      "source": "derived",
      "light": "cards/predict/4d0836c4ed29-light.svg",
      "dark": "cards/predict/4d0836c4ed29-dark.svg"
    },
    {
      "smiles": "C=CCC",
      "formula": "C4H8",
      "caption": "The same carbons, branched differently",
      "kind": "branch",
      "source": "derived",
      "light": "cards/predict/b24334aa53ba-light.svg",
      "dark": "cards/predict/b24334aa53ba-dark.svg"
    }
  ],
  "alcohol-pbr3": [
    {
      "smiles": "CCC(C)Br",
      "formula": "C4H9Br",
      "caption": "The same group on a different carbon",
      "kind": "regio",
      "source": "derived",
      "light": "cards/predict/7ac36dd00c40-light.svg",
      "dark": "cards/predict/7ac36dd00c40-dark.svg"
    },
    {
      "smiles": "C=CCCBr",
      "formula": "C4H7Br",
      "caption": "A double bond the conditions do not make",
      "kind": "unsaturated",
      "source": "derived",
      "light": "cards/predict/205eb25d97c8-light.svg",
      "dark": "cards/predict/205eb25d97c8-dark.svg"
    }
  ],
  "alcohol-to-halide": [
    {
      "smiles": "CC(C)CBr",
      "formula": "C4H9Br",
      "caption": "The same group on a different carbon",
      "kind": "regio",
      "source": "derived",
      "light": "cards/predict/3ab0ef3a0972-light.svg",
      "dark": "cards/predict/3ab0ef3a0972-dark.svg"
    },
    {
      "smiles": "CCCCBr",
      "formula": "C4H9Br",
      "caption": "What Alcohol to alkyl halide with PBr3 gives",
      "kind": "registry",
      "source": "alcohol-pbr3",
      "light": "cards/predict/5e882c2448c8-light.svg",
      "dark": "cards/predict/5e882c2448c8-dark.svg"
    }
  ],
  "aldol-addition": [
    {
      "smiles": "CC(O)C=CO",
      "formula": "C4H8O2",
      "caption": "A tautomer: the double bond on carbon instead",
      "kind": "tautomer",
      "source": "derived",
      "light": "cards/predict/5a0379ed9b78-light.svg",
      "dark": "cards/predict/5a0379ed9b78-dark.svg"
    },
    {
      "smiles": "CC=CC=O",
      "formula": "C4H6O",
      "caption": "What Aldol condensation gives",
      "kind": "sibling",
      "source": "aldol-condensation",
      "light": "cards/predict/e73ae8c6477c-light.svg",
      "dark": "cards/predict/e73ae8c6477c-dark.svg"
    }
  ],
  "aldol-condensation": [
    {
      "smiles": "C=CCC=O",
      "formula": "C4H6O",
      "caption": "The double bond one carbon over",
      "kind": "shifted",
      "source": "derived",
      "light": "cards/predict/b1ccc2caf805-light.svg",
      "dark": "cards/predict/b1ccc2caf805-dark.svg"
    },
    {
      "smiles": "CC(O)CC=O",
      "formula": "C4H8O2",
      "caption": "What Aldol addition gives",
      "kind": "sibling",
      "source": "aldol-addition",
      "light": "cards/predict/2c3a972266b2-light.svg",
      "dark": "cards/predict/2c3a972266b2-dark.svg"
    }
  ],
  "alpha-halogenation": [
    {
      "smiles": "OC(=CBr)c1ccccc1",
      "formula": "C8H7BrO",
      "caption": "A tautomer: the double bond on carbon instead",
      "kind": "tautomer",
      "source": "derived",
      "light": "cards/predict/8ced2e9b992b-light.svg",
      "dark": "cards/predict/8ced2e9b992b-dark.svg"
    },
    {
      "smiles": "OC(CBr)c1ccccc1",
      "formula": "C8H9BrO",
      "caption": "One reduction too far",
      "kind": "reduced",
      "source": "derived",
      "light": "cards/predict/ebae3c70b40f-light.svg",
      "dark": "cards/predict/ebae3c70b40f-dark.svg"
    }
  ],
  "claisen-condensation": [
    {
      "smiles": "C=C(O)CC(=O)OCC",
      "formula": "C6H10O3",
      "caption": "A tautomer: the double bond on carbon instead",
      "kind": "tautomer",
      "source": "derived",
      "light": "cards/predict/59652a9ee8f2-light.svg",
      "dark": "cards/predict/59652a9ee8f2-dark.svg"
    },
    {
      "smiles": "CCOC(=O)CC(C)O",
      "formula": "C6H12O3",
      "caption": "One reduction too far",
      "kind": "reduced",
      "source": "derived",
      "light": "cards/predict/eb19b16f83b4-light.svg",
      "dark": "cards/predict/eb19b16f83b4-dark.svg"
    }
  ],
  "clemmensen": [
    {
      "smiles": "Cc1ccc(C)cc1",
      "formula": "C8H10",
      "caption": "The same carbons, branched differently",
      "kind": "branch",
      "source": "derived",
      "light": "cards/predict/07cd55a1e1a9-light.svg",
      "dark": "cards/predict/07cd55a1e1a9-dark.svg"
    },
    {
      "smiles": "C=Cc1ccccc1",
      "formula": "C8H8",
      "caption": "A double bond the conditions do not make",
      "kind": "unsaturated",
      "source": "derived",
      "light": "cards/predict/8f6ed7c00299-light.svg",
      "dark": "cards/predict/8f6ed7c00299-dark.svg"
    }
  ],
  "cyanohydrin": [
    {
      "smiles": "N=CC(O)c1ccccc1",
      "formula": "C8H9NO",
      "caption": "One reduction too far",
      "kind": "reduced",
      "source": "derived",
      "light": "cards/predict/1b4a93e9124e-light.svg",
      "dark": "cards/predict/1b4a93e9124e-dark.svg"
    },
    {
      "smiles": "N#CCc1ccc(O)cc1",
      "formula": "C8H7NO",
      "caption": "The same group on a different carbon",
      "kind": "regio",
      "source": "derived",
      "light": "cards/predict/6564b75506c6-light.svg",
      "dark": "cards/predict/6564b75506c6-dark.svg"
    }
  ],
  "dibalh-to-aldehyde": [
    {
      "smiles": "O=C(O)c1ccccc1",
      "formula": "C7H6O2",
      "caption": "What Acidic ester hydrolysis gives",
      "kind": "sibling",
      "source": "ester-acidic-hydrolysis",
      "light": "cards/predict/aaba64840aca-light.svg",
      "dark": "cards/predict/aaba64840aca-dark.svg"
    },
    {
      "smiles": "OCc1ccccc1",
      "formula": "C7H8O",
      "caption": "One reduction too far",
      "kind": "reduced",
      "source": "derived",
      "light": "cards/predict/24703bb6824e-light.svg",
      "dark": "cards/predict/24703bb6824e-dark.svg"
    }
  ],
  "diels-alder": [
    {
      "smiles": "O=CC1C=CCCC1",
      "formula": "C7H10O",
      "caption": "The double bond one carbon over",
      "kind": "shifted",
      "source": "derived",
      "light": "cards/predict/00a56c4f4367-light.svg",
      "dark": "cards/predict/00a56c4f4367-dark.svg"
    },
    {
      "smiles": "OC=C1CC=CCC1",
      "formula": "C7H10O",
      "caption": "A tautomer: the double bond on carbon instead",
      "kind": "tautomer",
      "source": "derived",
      "light": "cards/predict/767c975a3628-light.svg",
      "dark": "cards/predict/767c975a3628-dark.svg"
    }
  ],
  "diene-1-4-addition": [
    {
      "smiles": "C=CC(C)Br",
      "formula": "C4H7Br",
      "caption": "The other end of the allyl system",
      "kind": "allylic",
      "source": "derived",
      "light": "cards/predict/d88f676c9931-light.svg",
      "dark": "cards/predict/d88f676c9931-dark.svg"
    },
    {
      "smiles": "C=CCCBr",
      "formula": "C4H7Br",
      "caption": "The double bond one carbon over",
      "kind": "shifted",
      "source": "derived",
      "light": "cards/predict/205eb25d97c8-light.svg",
      "dark": "cards/predict/205eb25d97c8-dark.svg"
    }
  ],
  "eas-bromination": [
    {
      "smiles": "Brc1ccc(Br)cc1",
      "formula": "C6H4Br2",
      "caption": "Substituted twice",
      "kind": "twice",
      "source": "derived",
      "light": "cards/predict/e3797379b447-light.svg",
      "dark": "cards/predict/e3797379b447-dark.svg"
    },
    {
      "smiles": "Brc1cccc(Br)c1",
      "formula": "C6H4Br2",
      "caption": "Substituted twice",
      "kind": "twice",
      "source": "derived",
      "light": "cards/predict/136a86243881-light.svg",
      "dark": "cards/predict/136a86243881-dark.svg"
    }
  ],
  "epoxidation-mcpba": [
    {
      "smiles": "CC(O)CC=O",
      "formula": "C4H8O2",
      "caption": "What Aldol addition gives",
      "kind": "registry",
      "source": "aldol-addition",
      "light": "cards/predict/2c3a972266b2-light.svg",
      "dark": "cards/predict/2c3a972266b2-dark.svg"
    },
    {
      "smiles": "CC=CC=O",
      "formula": "C4H6O",
      "caption": "What Aldol condensation gives",
      "kind": "registry",
      "source": "aldol-condensation",
      "light": "cards/predict/e73ae8c6477c-light.svg",
      "dark": "cards/predict/e73ae8c6477c-dark.svg"
    }
  ],
  "ester-acidic-hydrolysis": [
    {
      "smiles": "O=Cc1ccccc1",
      "formula": "C7H6O",
      "caption": "What DIBAL-H partial reduction of an ester gives",
      "kind": "sibling",
      "source": "dibalh-to-aldehyde",
      "light": "cards/predict/da3341b60b14-light.svg",
      "dark": "cards/predict/da3341b60b14-dark.svg"
    },
    {
      "smiles": "O=Cc1ccc(O)cc1",
      "formula": "C7H6O2",
      "caption": "The same group on a different carbon",
      "kind": "regio",
      "source": "derived",
      "light": "cards/predict/81152bb7c821-light.svg",
      "dark": "cards/predict/81152bb7c821-dark.svg"
    }
  ],
  "fischer-esterification": [
    {
      "smiles": "COc1ccc(C=O)cc1",
      "formula": "C8H8O2",
      "caption": "The same group on a different carbon",
      "kind": "regio",
      "source": "derived",
      "light": "cards/predict/a49258eda0fb-light.svg",
      "dark": "cards/predict/a49258eda0fb-dark.svg"
    },
    {
      "smiles": "CC(=O)c1ccccc1",
      "formula": "C8H8O",
      "caption": "What Friedel-Crafts acylation gives",
      "kind": "registry",
      "source": "friedel-crafts-acylation",
      "light": "cards/predict/33134a8efc4b-light.svg",
      "dark": "cards/predict/33134a8efc4b-dark.svg"
    }
  ],
  "friedel-crafts-acylation": [
    {
      "smiles": "C=C(O)c1ccccc1",
      "formula": "C8H8O",
      "caption": "A tautomer: the double bond on carbon instead",
      "kind": "tautomer",
      "source": "derived",
      "light": "cards/predict/2e6422b0d1a4-light.svg",
      "dark": "cards/predict/2e6422b0d1a4-dark.svg"
    },
    {
      "smiles": "CC(O)c1ccccc1",
      "formula": "C8H10O",
      "caption": "One reduction too far",
      "kind": "reduced",
      "source": "derived",
      "light": "cards/predict/574cee0172c2-light.svg",
      "dark": "cards/predict/574cee0172c2-dark.svg"
    }
  ],
  "gilman-to-ketone": [
    {
      "smiles": "C=C(O)c1ccccc1",
      "formula": "C8H8O",
      "caption": "A tautomer: the double bond on carbon instead",
      "kind": "tautomer",
      "source": "derived",
      "light": "cards/predict/2e6422b0d1a4-light.svg",
      "dark": "cards/predict/2e6422b0d1a4-dark.svg"
    },
    {
      "smiles": "CC(O)c1ccccc1",
      "formula": "C8H10O",
      "caption": "One reduction too far",
      "kind": "reduced",
      "source": "derived",
      "light": "cards/predict/574cee0172c2-light.svg",
      "dark": "cards/predict/574cee0172c2-dark.svg"
    }
  ],
  "grignard-addition-ketone": [
    {
      "smiles": "CC(C)c1ccc(O)cc1",
      "formula": "C9H12O",
      "caption": "The same group on a different carbon",
      "kind": "regio",
      "source": "derived",
      "light": "cards/predict/da962cde00db-light.svg",
      "dark": "cards/predict/da962cde00db-dark.svg"
    },
    {
      "smiles": "CC(C)c1cccc(O)c1",
      "formula": "C9H12O",
      "caption": "The same group on a different carbon",
      "kind": "regio",
      "source": "derived",
      "light": "cards/predict/3f373f38bb50-light.svg",
      "dark": "cards/predict/3f373f38bb50-dark.svg"
    }
  ],
  "imine-formation": [
    {
      "smiles": "C=C(NC)c1ccccc1",
      "formula": "C9H11N",
      "caption": "A tautomer: the double bond on carbon instead",
      "kind": "tautomer",
      "source": "derived",
      "light": "cards/predict/207e7c3713bc-light.svg",
      "dark": "cards/predict/207e7c3713bc-dark.svg"
    },
    {
      "smiles": "CNC(C)c1ccccc1",
      "formula": "C9H13N",
      "caption": "One reduction too far",
      "kind": "reduced",
      "source": "derived",
      "light": "cards/predict/be001112d14d-light.svg",
      "dark": "cards/predict/be001112d14d-dark.svg"
    }
  ],
  "jones-oxidation": [
    {
      "smiles": "O=Cc1ccc(O)cc1",
      "formula": "C7H6O2",
      "caption": "The same group on a different carbon",
      "kind": "regio",
      "source": "derived",
      "light": "cards/predict/81152bb7c821-light.svg",
      "dark": "cards/predict/81152bb7c821-dark.svg"
    },
    {
      "smiles": "O=Cc1ccccc1",
      "formula": "C7H6O",
      "caption": "What DIBAL-H partial reduction of an ester gives",
      "kind": "registry",
      "source": "dibalh-to-aldehyde",
      "light": "cards/predict/da3341b60b14-light.svg",
      "dark": "cards/predict/da3341b60b14-dark.svg"
    }
  ],
  "lialh4-reduction": [
    {
      "smiles": "O=Cc1ccccc1",
      "formula": "C7H6O",
      "caption": "What DIBAL-H partial reduction of an ester gives",
      "kind": "sibling",
      "source": "dibalh-to-aldehyde",
      "light": "cards/predict/da3341b60b14-light.svg",
      "dark": "cards/predict/da3341b60b14-dark.svg"
    },
    {
      "smiles": "Cc1ccc(O)cc1",
      "formula": "C7H8O",
      "caption": "The same group on a different carbon",
      "kind": "regio",
      "source": "derived",
      "light": "cards/predict/188d8de09c6f-light.svg",
      "dark": "cards/predict/188d8de09c6f-dark.svg"
    }
  ],
  "malonic-ester-synthesis": [
    {
      "smiles": "CC=C(O)O",
      "formula": "C3H6O2",
      "caption": "A tautomer: the double bond on carbon instead",
      "kind": "tautomer",
      "source": "derived",
      "light": "cards/predict/26274c0e2400-light.svg",
      "dark": "cards/predict/26274c0e2400-dark.svg"
    },
    {
      "smiles": "CC(O)C=O",
      "formula": "C3H6O2",
      "caption": "The same group on a different carbon",
      "kind": "regio",
      "source": "derived",
      "light": "cards/predict/3a272bbb380f-light.svg",
      "dark": "cards/predict/3a272bbb380f-dark.svg"
    }
  ],
  "michael-addition": [
    {
      "smiles": "C=C(O)CCCC(C)=O",
      "formula": "C7H12O2",
      "caption": "A tautomer: the double bond on carbon instead",
      "kind": "tautomer",
      "source": "derived",
      "light": "cards/predict/ecc4ab521dc0-light.svg",
      "dark": "cards/predict/ecc4ab521dc0-dark.svg"
    },
    {
      "smiles": "CC(=O)CCCC(C)O",
      "formula": "C7H14O2",
      "caption": "One reduction too far",
      "kind": "reduced",
      "source": "derived",
      "light": "cards/predict/433c29563ab8-light.svg",
      "dark": "cards/predict/433c29563ab8-dark.svg"
    }
  ],
  "nabh4-reduction": [
    {
      "smiles": "CCc1ccc(O)cc1",
      "formula": "C8H10O",
      "caption": "The same group on a different carbon",
      "kind": "regio",
      "source": "derived",
      "light": "cards/predict/e79711f32bac-light.svg",
      "dark": "cards/predict/e79711f32bac-dark.svg"
    },
    {
      "smiles": "C=C(O)c1ccccc1",
      "formula": "C8H8O",
      "caption": "A double bond the conditions do not make",
      "kind": "unsaturated",
      "source": "derived",
      "light": "cards/predict/2e6422b0d1a4-light.svg",
      "dark": "cards/predict/2e6422b0d1a4-dark.svg"
    }
  ],
  "nbs-allylic": [
    {
      "smiles": "CC=CCBr",
      "formula": "C4H7Br",
      "caption": "The other end of the allyl system",
      "kind": "allylic",
      "source": "derived",
      "light": "cards/predict/605e1fdb876f-light.svg",
      "dark": "cards/predict/605e1fdb876f-dark.svg"
    },
    {
      "smiles": "CC=C(C)Br",
      "formula": "C4H7Br",
      "caption": "The double bond one carbon over",
      "kind": "shifted",
      "source": "derived",
      "light": "cards/predict/48d226626f26-light.svg",
      "dark": "cards/predict/48d226626f26-dark.svg"
    }
  ],
  "nitration": [
    {
      "smiles": "O=[N+]([O-])c1ccc([N+](=O)[O-])cc1",
      "formula": "C6H4N2O4",
      "caption": "Substituted twice",
      "kind": "twice",
      "source": "derived",
      "light": "cards/predict/35a13ee1c7c9-light.svg",
      "dark": "cards/predict/35a13ee1c7c9-dark.svg"
    },
    {
      "smiles": "O=[N+]([O-])c1cccc([N+](=O)[O-])c1",
      "formula": "C6H4N2O4",
      "caption": "Substituted twice",
      "kind": "twice",
      "source": "derived",
      "light": "cards/predict/bd345d4e3ea9-light.svg",
      "dark": "cards/predict/bd345d4e3ea9-dark.svg"
    }
  ],
  "nitrile-basic-hydrolysis": [
    {
      "smiles": "O=Cc1ccc([O-])cc1",
      "formula": "C7H5O2-",
      "caption": "The same group on a different carbon",
      "kind": "regio",
      "source": "derived",
      "light": "cards/predict/5bba23227da5-light.svg",
      "dark": "cards/predict/5bba23227da5-dark.svg"
    },
    {
      "smiles": "O=Cc1ccccc1",
      "formula": "C7H6O",
      "caption": "What DIBAL-H partial reduction of an ester gives",
      "kind": "registry",
      "source": "dibalh-to-aldehyde",
      "light": "cards/predict/da3341b60b14-light.svg",
      "dark": "cards/predict/da3341b60b14-dark.svg"
    }
  ],
  "nitrile-formation": [
    {
      "smiles": "N=Cc1ccccc1",
      "formula": "C7H7N",
      "caption": "One reduction too far",
      "kind": "reduced",
      "source": "derived",
      "light": "cards/predict/2d12d1dbeea7-light.svg",
      "dark": "cards/predict/2d12d1dbeea7-dark.svg"
    },
    {
      "smiles": "NCc1ccccc1",
      "formula": "C7H9N",
      "caption": "What Nitrile reduction to a primary amine gives",
      "kind": "registry",
      "source": "nitrile-reduction",
      "light": "cards/predict/d62c8648e660-light.svg",
      "dark": "cards/predict/d62c8648e660-dark.svg"
    }
  ],
  "nitrile-reduction": [
    {
      "smiles": "Cc1ccc(N)cc1",
      "formula": "C7H9N",
      "caption": "The same group on a different carbon",
      "kind": "regio",
      "source": "derived",
      "light": "cards/predict/c66f269f67ab-light.svg",
      "dark": "cards/predict/c66f269f67ab-dark.svg"
    },
    {
      "smiles": "Cc1cccc(N)c1",
      "formula": "C7H9N",
      "caption": "The same group on a different carbon",
      "kind": "regio",
      "source": "derived",
      "light": "cards/predict/b3e57b2c2b6b-light.svg",
      "dark": "cards/predict/b3e57b2c2b6b-dark.svg"
    }
  ],
  "pcc-oxidation": [
    {
      "smiles": "CCC=CO",
      "formula": "C4H8O",
      "caption": "A tautomer: the double bond on carbon instead",
      "kind": "tautomer",
      "source": "derived",
      "light": "cards/predict/341e0749480b-light.svg",
      "dark": "cards/predict/341e0749480b-dark.svg"
    },
    {
      "smiles": "C=CCC=O",
      "formula": "C4H6O",
      "caption": "A double bond the conditions do not make",
      "kind": "unsaturated",
      "source": "derived",
      "light": "cards/predict/b1ccc2caf805-light.svg",
      "dark": "cards/predict/b1ccc2caf805-dark.svg"
    }
  ],
  "robinson-annulation": [
    {
      "smiles": "O=C1CCC2=C(CCCC2)C1",
      "formula": "C10H14O",
      "caption": "The double bond one carbon over",
      "kind": "shifted",
      "source": "derived",
      "light": "cards/predict/d19e42af3f15-light.svg",
      "dark": "cards/predict/d19e42af3f15-dark.svg"
    },
    {
      "smiles": "OC1=CCC2CCCCC2=C1",
      "formula": "C10H14O",
      "caption": "A tautomer: the double bond on carbon instead",
      "kind": "tautomer",
      "source": "derived",
      "light": "cards/predict/7d91523a2db2-light.svg",
      "dark": "cards/predict/7d91523a2db2-dark.svg"
    }
  ],
  "sandmeyer": [
    {
      "smiles": "Brc1ccc(Br)cc1",
      "formula": "C6H4Br2",
      "caption": "Substituted twice",
      "kind": "twice",
      "source": "derived",
      "light": "cards/predict/e3797379b447-light.svg",
      "dark": "cards/predict/e3797379b447-dark.svg"
    },
    {
      "smiles": "Brc1cccc(Br)c1",
      "formula": "C6H4Br2",
      "caption": "Substituted twice",
      "kind": "twice",
      "source": "derived",
      "light": "cards/predict/136a86243881-light.svg",
      "dark": "cards/predict/136a86243881-dark.svg"
    }
  ],
  "socl2-acid-to-chloride": [
    {
      "smiles": "O=Cc1ccc(Cl)cc1",
      "formula": "C7H5ClO",
      "caption": "The same group on a different carbon",
      "kind": "regio",
      "source": "derived",
      "light": "cards/predict/27a2fd432494-light.svg",
      "dark": "cards/predict/27a2fd432494-dark.svg"
    },
    {
      "smiles": "O=Cc1cccc(Cl)c1",
      "formula": "C7H5ClO",
      "caption": "The same group on a different carbon",
      "kind": "regio",
      "source": "derived",
      "light": "cards/predict/67b1733a5818-light.svg",
      "dark": "cards/predict/67b1733a5818-dark.svg"
    }
  ],
  "wittig-olefination": [
    {
      "smiles": "CC(C)c1ccccc1",
      "formula": "C9H12",
      "caption": "One reduction too far",
      "kind": "reduced",
      "source": "derived",
      "light": "cards/predict/d03bdfab449c-light.svg",
      "dark": "cards/predict/d03bdfab449c-dark.svg"
    },
    {
      "smiles": "C=Cc1ccc(C)cc1",
      "formula": "C9H10",
      "caption": "The same carbons, branched differently",
      "kind": "branch",
      "source": "derived",
      "light": "cards/predict/619b48d1cc6d-light.svg",
      "dark": "cards/predict/619b48d1cc6d-dark.svg"
    }
  ],
  "wolff-kishner": [
    {
      "smiles": "Cc1ccc(C)cc1",
      "formula": "C8H10",
      "caption": "The same carbons, branched differently",
      "kind": "branch",
      "source": "derived",
      "light": "cards/predict/07cd55a1e1a9-light.svg",
      "dark": "cards/predict/07cd55a1e1a9-dark.svg"
    },
    {
      "smiles": "C=Cc1ccccc1",
      "formula": "C8H8",
      "caption": "A double bond the conditions do not make",
      "kind": "unsaturated",
      "source": "derived",
      "light": "cards/predict/8f6ed7c00299-light.svg",
      "dark": "cards/predict/8f6ed7c00299-dark.svg"
    }
  ]
};

/** Registry reactions with no honest predict step: fewer than two options pass. */
export const PREDICT_GAPS: readonly string[] = ["diazonium-formation", "epoxide-opening-base", "ether-cleavage", "periodic-cleavage"];
