// GENERATED by scripts/build_card_distractors.py. Do not edit by hand.
// The options for the Cards run's predict step, derived with RDKit; the rules
// they meet are in the script's header and pinned in test/cardsRun.test.ts.

export interface PredictDistractor {
  /** Canonical SMILES. Data for tests; never shown to a student. */
  readonly smiles: string;
  /** RDKit's formula of the same structure. */
  readonly formula: string;
  /** What this structure is relative to the answer, shown after the pick. */
  readonly caption: string;
  readonly kind: string;
  /** "derived", or the registry reaction this structure comes from. */
  readonly source: string;
  /** Morgan (radius 2) Tanimoto to the closest start, the rule 4 measure. */
  readonly similarity: number;
  /** Rule 5's classes, from RDKit: net formal charge, and enol/enamine form. */
  readonly charge: number;
  readonly enol: boolean;
  readonly light?: string;
  readonly dark?: string;
}

/** The answer, drawn in the options' own style, and its similarity to the start. */
export interface PredictAnswer {
  readonly similarity: number;
  readonly charge: number;
  readonly enol: boolean;
  /** Rule 6: what this card's own data or mechanism makes; never a wrong option. */
  readonly ownProducts: readonly string[];
  readonly light?: string;
  readonly dark?: string;
}

export const PREDICT_DISTRACTORS: Readonly<Record<string, readonly PredictDistractor[]>> = {
  "acetylide-addition": [
    {
      "smiles": "CC#COCc1ccccc1",
      "formula": "C10H10O",
      "caption": "The new group on the oxygen instead",
      "kind": "on-oxygen",
      "source": "derived",
      "similarity": 0.2,
      "charge": 0,
      "enol": false,
      "light": "cards/predict/b64a6c4867e2-light.svg",
      "dark": "cards/predict/b64a6c4867e2-dark.svg"
    },
    {
      "smiles": "OCC#CCc1ccccc1",
      "formula": "C10H10O",
      "caption": "The same group on a different carbon",
      "kind": "regio",
      "source": "derived",
      "similarity": 0.214,
      "charge": 0,
      "enol": false,
      "light": "cards/predict/9d8b8bba1ce6-light.svg",
      "dark": "cards/predict/9d8b8bba1ce6-dark.svg"
    }
  ],
  "aldol-addition": [
    {
      "smiles": "CCOCC=O",
      "formula": "C4H8O2",
      "caption": "The new group on the oxygen instead",
      "kind": "on-oxygen",
      "source": "derived",
      "similarity": 0.235,
      "charge": 0,
      "enol": false,
      "light": "cards/predict/e6c091254dcf-light.svg",
      "dark": "cards/predict/e6c091254dcf-dark.svg"
    },
    {
      "smiles": "CCC(O)C=O",
      "formula": "C4H8O2",
      "caption": "The same group on a different carbon",
      "kind": "regio",
      "source": "derived",
      "similarity": 0.235,
      "charge": 0,
      "enol": false,
      "light": "cards/predict/cf4680dfa822-light.svg",
      "dark": "cards/predict/cf4680dfa822-dark.svg"
    }
  ],
  "dibalh-to-aldehyde": [
    {
      "smiles": "O=C(O)c1ccccc1",
      "formula": "C7H6O2",
      "caption": "What Acidic ester hydrolysis gives",
      "kind": "sibling:nucleophilic acyl substitution",
      "source": "ester-acidic-hydrolysis",
      "similarity": 0.5,
      "charge": 0,
      "enol": false,
      "light": "cards/predict/aaba64840aca-light.svg",
      "dark": "cards/predict/aaba64840aca-dark.svg"
    },
    {
      "smiles": "OCc1ccccc1",
      "formula": "C7H8O",
      "caption": "What Lithium aluminium hydride reduction gives",
      "kind": "sibling:reduction",
      "source": "lialh4-reduction",
      "similarity": 0.269,
      "charge": 0,
      "enol": false,
      "light": "cards/predict/24703bb6824e-light.svg",
      "dark": "cards/predict/24703bb6824e-dark.svg"
    }
  ],
  "diene-1-4-addition": [
    {
      "smiles": "C=CC(C)Br",
      "formula": "C4H7Br",
      "caption": "The other end of the allyl system",
      "kind": "allylic",
      "source": "derived",
      "similarity": 0.231,
      "charge": 0,
      "enol": false,
      "light": "cards/predict/d88f676c9931-light.svg",
      "dark": "cards/predict/d88f676c9931-dark.svg"
    },
    {
      "smiles": "C=CCCBr",
      "formula": "C4H7Br",
      "caption": "The double bond one carbon over",
      "kind": "shifted",
      "source": "derived",
      "similarity": 0.214,
      "charge": 0,
      "enol": false,
      "light": "cards/predict/205eb25d97c8-light.svg",
      "dark": "cards/predict/205eb25d97c8-dark.svg"
    }
  ],
  "grignard-addition-ketone": [
    {
      "smiles": "COC(C)c1ccccc1",
      "formula": "C9H12O",
      "caption": "The new group on the oxygen instead",
      "kind": "on-oxygen",
      "source": "derived",
      "similarity": 0.259,
      "charge": 0,
      "enol": false,
      "light": "cards/predict/fdc25d91a890-light.svg",
      "dark": "cards/predict/fdc25d91a890-dark.svg"
    },
    {
      "smiles": "CC(CO)c1ccccc1",
      "formula": "C9H12O",
      "caption": "The same group on a different carbon",
      "kind": "regio",
      "source": "derived",
      "similarity": 0.296,
      "charge": 0,
      "enol": false,
      "light": "cards/predict/9054989f0091-light.svg",
      "dark": "cards/predict/9054989f0091-dark.svg"
    }
  ],
  "lialh4-reduction": [
    {
      "smiles": "O=Cc1ccccc1",
      "formula": "C7H6O",
      "caption": "What DIBAL-H partial reduction of an ester gives",
      "kind": "sibling:reduction",
      "source": "dibalh-to-aldehyde",
      "similarity": 0.269,
      "charge": 0,
      "enol": false,
      "light": "cards/predict/da3341b60b14-light.svg",
      "dark": "cards/predict/da3341b60b14-dark.svg"
    },
    {
      "smiles": "O=C(O)c1ccccc1",
      "formula": "C7H6O2",
      "caption": "What Acidic ester hydrolysis gives",
      "kind": "sibling:nucleophilic acyl substitution",
      "source": "ester-acidic-hydrolysis",
      "similarity": 0.5,
      "charge": 0,
      "enol": false,
      "light": "cards/predict/aaba64840aca-light.svg",
      "dark": "cards/predict/aaba64840aca-dark.svg"
    }
  ],
  "malonic-ester-synthesis": [
    {
      "smiles": "CCOC(=O)C(C)C(=O)OCC",
      "formula": "C8H14O4",
      "caption": "An intermediate: the reaction stops short",
      "kind": "intermediate",
      "source": "malonic-ester-synthesis",
      "similarity": 0.476,
      "charge": 0,
      "enol": false,
      "light": "cards/predict/55bd0b3366fa-light.svg",
      "dark": "cards/predict/55bd0b3366fa-dark.svg"
    },
    {
      "smiles": "CC(C)C(=O)O",
      "formula": "C4H8O2",
      "caption": "The reagent adding a second time",
      "kind": "over",
      "source": "derived",
      "similarity": 0.19,
      "charge": 0,
      "enol": false,
      "light": "cards/predict/c4e3082b583a-light.svg",
      "dark": "cards/predict/c4e3082b583a-dark.svg"
    }
  ],
  "nbs-allylic": [
    {
      "smiles": "CCC(Br)CBr",
      "formula": "C4H8Br2",
      "caption": "Br2 added across a double bond instead",
      "kind": "addition",
      "source": "derived",
      "similarity": 0.158,
      "charge": 0,
      "enol": false,
      "light": "cards/predict/2a9bc3da800c-light.svg",
      "dark": "cards/predict/2a9bc3da800c-dark.svg"
    },
    {
      "smiles": "C=CCCBr",
      "formula": "C4H7Br",
      "caption": "The same group on a different carbon",
      "kind": "regio",
      "source": "derived",
      "similarity": 0.312,
      "charge": 0,
      "enol": false,
      "light": "cards/predict/205eb25d97c8-light.svg",
      "dark": "cards/predict/205eb25d97c8-dark.svg"
    }
  ],
  "pcc-oxidation": [
    {
      "smiles": "CCCC(=O)O",
      "formula": "C4H8O2",
      "caption": "One oxidation too far",
      "kind": "oxidised",
      "source": "derived",
      "similarity": 0.263,
      "charge": 0,
      "enol": false,
      "light": "cards/predict/1f78679d2856-light.svg",
      "dark": "cards/predict/1f78679d2856-dark.svg"
    },
    {
      "smiles": "CC=CC=O",
      "formula": "C4H6O",
      "caption": "A double bond the conditions do not make",
      "kind": "unsaturated",
      "source": "derived",
      "similarity": 0.048,
      "charge": 0,
      "enol": false,
      "light": "cards/predict/e73ae8c6477c-light.svg",
      "dark": "cards/predict/e73ae8c6477c-dark.svg"
    }
  ],
  "robinson-annulation": [
    {
      "smiles": "CC(=O)CCC1CCCCC1=O",
      "formula": "C10H16O2",
      "caption": "An intermediate: the reaction stops short",
      "kind": "intermediate",
      "source": "robinson-annulation",
      "similarity": 0.226,
      "charge": 0,
      "enol": false,
      "light": "cards/predict/1623120b99b0-light.svg",
      "dark": "cards/predict/1623120b99b0-dark.svg"
    },
    {
      "smiles": "O=C1CCC2CCCC=C2C1",
      "formula": "C10H14O",
      "caption": "The double bond one carbon over",
      "kind": "shifted",
      "source": "derived",
      "similarity": 0.241,
      "charge": 0,
      "enol": false,
      "light": "cards/predict/c6d4383a91fe-light.svg",
      "dark": "cards/predict/c6d4383a91fe-dark.svg"
    }
  ]
};

export const PREDICT_ANSWERS: Readonly<Record<string, PredictAnswer>> = {
  "acetylide-addition": {
    "similarity": 0.207,
    "charge": 0,
    "enol": false,
    "ownProducts": [
      "CC#CC(O)c1ccccc1"
    ],
    "light": "cards/predict/a26bb2613659-light.svg",
    "dark": "cards/predict/a26bb2613659-dark.svg"
  },
  "aldol-addition": {
    "similarity": 0.235,
    "charge": 0,
    "enol": false,
    "ownProducts": [
      "CC(O)CC=O"
    ],
    "light": "cards/predict/2c3a972266b2-light.svg",
    "dark": "cards/predict/2c3a972266b2-dark.svg"
  },
  "dibalh-to-aldehyde": {
    "similarity": 0.269,
    "charge": 0,
    "enol": false,
    "ownProducts": [
      "CO",
      "O=Cc1ccccc1"
    ],
    "light": "cards/predict/da3341b60b14-light.svg",
    "dark": "cards/predict/da3341b60b14-dark.svg"
  },
  "diene-1-4-addition": {
    "similarity": 0.062,
    "charge": 0,
    "enol": false,
    "ownProducts": [
      "CC=CCBr"
    ],
    "light": "cards/predict/605e1fdb876f-light.svg",
    "dark": "cards/predict/605e1fdb876f-dark.svg"
  },
  "grignard-addition-ketone": {
    "similarity": 0.333,
    "charge": 0,
    "enol": false,
    "ownProducts": [
      "CC(C)(O)c1ccccc1"
    ],
    "light": "cards/predict/4e2582d0e380-light.svg",
    "dark": "cards/predict/4e2582d0e380-dark.svg"
  },
  "lialh4-reduction": {
    "similarity": 0.269,
    "charge": 0,
    "enol": false,
    "ownProducts": [
      "CO",
      "OCc1ccccc1"
    ],
    "light": "cards/predict/24703bb6824e-light.svg",
    "dark": "cards/predict/24703bb6824e-dark.svg"
  },
  "malonic-ester-synthesis": {
    "similarity": 0.316,
    "charge": 0,
    "enol": false,
    "ownProducts": [
      "CCC(=O)O",
      "CCO",
      "I",
      "O=C=O"
    ],
    "light": "cards/predict/103f2657047a-light.svg",
    "dark": "cards/predict/103f2657047a-dark.svg"
  },
  "nbs-allylic": {
    "similarity": 0.25,
    "charge": 0,
    "enol": false,
    "ownProducts": [
      "C=CC(C)Br",
      "CC=CCBr",
      "O=C1CCC(=O)N1"
    ],
    "light": "cards/predict/d88f676c9931-light.svg",
    "dark": "cards/predict/d88f676c9931-dark.svg"
  },
  "pcc-oxidation": {
    "similarity": 0.211,
    "charge": 0,
    "enol": false,
    "ownProducts": [
      "CCCC=O"
    ],
    "light": "cards/predict/8952c0b61fbf-light.svg",
    "dark": "cards/predict/8952c0b61fbf-dark.svg"
  },
  "robinson-annulation": {
    "similarity": 0.259,
    "charge": 0,
    "enol": false,
    "ownProducts": [
      "O",
      "O=C1C=C2CCCCC2CC1"
    ],
    "light": "cards/predict/043bf829dd01-light.svg",
    "dark": "cards/predict/043bf829dd01-dark.svg"
  }
};

/** Registry reactions with no honest predict step: no pair of wrong options meets the rules. */
export const PREDICT_GAPS: readonly string[] = ["acetal-protection", "acidchloride-to-amide", "alcohol-dehydration", "alcohol-pbr3", "alcohol-to-halide", "aldol-condensation", "alpha-halogenation", "claisen-condensation", "clemmensen", "cyanohydrin", "diazonium-formation", "diels-alder", "eas-bromination", "epoxidation-mcpba", "epoxide-opening-base", "ester-acidic-hydrolysis", "ether-cleavage", "fischer-esterification", "friedel-crafts-acylation", "gilman-to-ketone", "imine-formation", "jones-oxidation", "michael-addition", "nabh4-reduction", "nitration", "nitrile-basic-hydrolysis", "nitrile-formation", "nitrile-reduction", "periodic-cleavage", "sandmeyer", "socl2-acid-to-chloride", "wittig-olefination", "wolff-kishner"];
