/**
 * Reaction cards, built from the authored reaction data. Read this header
 * before trusting anything in this file.
 *
 * THE OWNER'S DECISION (17 Sep): the reaction card's front shows reactants
 * plus reagents on one side of the arrow and products on the other, with the
 * temperature on the face; tapping reveals the optional labelled extras (Keq,
 * pKa, 1,2 against 1,4 selectivity, electronegativity, resonance notes).
 *
 * THE CHEMISTRY RULE, and it shapes every function here: chemistry shown to a
 * student is derived from authored data or RDKit, never recalled. Everything
 * this file writes onto a card is lifted VERBATIM out of data/reactions.ts,
 * which is generated by scripts/build_curriculum.py and RDKit-checked. A
 * field the data does not carry (a pKa, a Keq) is left ABSENT rather than
 * filled in from a model's memory, and the face renders only what exists.
 *
 * THE ID IS DERIVED, NEVER MINTED, per cards/types.ts's invariant: the same
 * reaction saved twice, or saved on the draw page and later seeded, is ONE
 * card that keeps its interval history, not two cards with rival schedules.
 *
 * Pure: no storage, no clock reads (now arrives as an argument), no React.
 * The store and the surfaces sit on the other side of this file.
 */

import { REACTIONS, type Stage, type StagedReaction } from "../../data/reactions";
import type { Card, CardId, ReactionCardArt, ReactionReveal } from "./types";

// The reveal vocabulary (REVEAL_ORDER, REVEAL_LABELS, presentReveal) lives in
// types.ts with the shapes it describes, so the composer can reach it without
// pulling this file's REACTIONS import into its bundle.

/* ------------------------------------------------------------------ */
/* Building a card from one authored reaction                           */
/* ------------------------------------------------------------------ */

/** The stable id. `reaction:` is its own namespace beside `mistake:` etc. */
export function reactionCardId(reactionId: string): CardId {
  return `reaction:${reactionId}`;
}

/** "-78 °C", from the number the data carries. */
export function temperatureLabel(celsius: number): string {
  return `${celsius} °C`;
}

/**
 * BOTTLE LABELS FOR THE STRUCTURE STRINGS, and this table is a chemistry-truth
 * fix, not a cosmetic one. The data lists a stage's mechanistic species first
 * and its bottle label last, so the last entry is usually already a label
 * ("NaBH4", "LiAlH4", "PBr3"). For eleven species there is no second entry and
 * the last one IS the SMILES, which the face then printed raw: imine formation
 * showed "CN", and a sophomore reads that as cyanide when it is methylamine.
 * Wolff-Kishner showed "NN" for hydrazine, Fischer esterification "CO" for
 * methanol.
 *
 * EVERY LABEL IS JUSTIFIED BY WHAT THE REPO DATA ALREADY SAYS THE SPECIES IS,
 * per the derive-never-recall rule. The justification for each, in the data:
 *
 *   [H3O+]      brackets stripped. Aqueous acid; every stage carrying it has
 *               solvent "water" and acid_base "acidic"
 *   [OH-]       brackets stripped and named. NOT "NaOH": aldol-condensation
 *               lists ["[OH-]","NaOH"] and wolff-kishner lists ["[OH-]","KOH"],
 *               so the counterion is a thing the data states per stage, and
 *               michael-addition and robinson-annulation state none at all
 *   NN          wolff-kishner, whose own notes say "Hydrazone forms first"
 *   CN          acidchloride-to-amide names this reactant "methylamine" in
 *               reactant_labels; imine-formation's product is "N-methyl imine"
 *   CO          fischer-esterification names this reactant "methanol"
 *   OCCO        transcribed from the structure, no name added
 *   BrBr        transcribed from the structure, no name added
 *   CC#[C-]     acetylide-addition's notes say "Acetylide from terminal alkyne"
 *   O=S(Cl)Cl   the reaction's own id is socl2-acid-to-chloride
 *   the ylide   wittig-olefination's notes say "Ylide from CH3-PPh3+"
 *   C=CC=O      diels-alder names this reactant "acrolein" in reactant_labels
 *
 * A structure string with no entry here falls back to the stage's FIRST
 * reagent rather than shipping brackets to a student.
 */
export const REAGENT_LABELS: Readonly<Record<string, string>> = Object.freeze({
  "[H3O+]": "H3O+",
  "[OH-]": "hydroxide",
  NN: "H2NNH2",
  CN: "CH3NH2",
  CO: "CH3OH",
  OCCO: "HOCH2CH2OH",
  BrBr: "Br2",
  // Prop-1-ynyl, NOT acetylide: the methyl is in the structure and in the
  // product ("1-phenyl-2-butyn-1-ol"), so a bare "acetylide" would have a
  // student draw HC#C- and land on the wrong alcohol.
  "CC#[C-]": "CH3C#C-",
  "O=S(Cl)Cl": "SOCl2",
  "[CH2-][P+](c1ccccc1)(c1ccccc1)c1ccccc1": "Ph3P=CH2",
  "C=CC=O": "acrolein",
});

/**
 * Whether a token is a structure string rather than a bottle label. Brackets
 * and bond symbols are the honest test: they cannot appear in a formula a
 * bottle wears, and every other SMILES in this registry ("CN", "CO") is
 * letter-for-letter indistinguishable from a formula, which is exactly why
 * those need the table above rather than a heuristic.
 */
function isSmilesShaped(token: string): boolean {
  return /[[\]=#]/.test(token);
}

/**
 * One stage's bottle label, or "" when the data has no label to give.
 *
 * THE FALLBACK USED TO BE reagents[0], AND IT COULD NOT PROTECT. On every
 * stage this table resolves, the array holds ONE entry, so reagents[0] is the
 * same token that just failed; and where a stage holds two, the first is the
 * mechanistic species ("[BH4-]", "[CH3-]"), which is the MORE structural of
 * the pair. The old rule therefore reached for the worst candidate available
 * and shipped it. A 44th reaction with one bracketed reagent would have put
 * "[BH4-]" in front of a student.
 *
 * So the last resort is silence: try the last token, then any earlier token
 * that reads as a bottle label, then nothing. The reagent line drops empty
 * stages, and a card with no reagent line says less rather than something
 * false. See REAGENT_LABELS for the rule and the table.
 */
export function stageReagentLabel(stage: Stage): string {
  for (const token of [...stage.reagents].reverse()) {
    const labelled = REAGENT_LABELS[token];
    if (labelled !== undefined) return labelled;
    if (!isSmilesShaped(token)) return token;
  }
  return "";
}

/**
 * "CH3MgBr; then H3O+" from the staged reagents, each stage named by
 * `stageReagentLabel`.
 */
export function stagedReagentLine(reaction: StagedReaction): string {
  // Consecutive stages that name the same reagent say it once. A second
  // stage is often heat or time rather than a new bottle, and the line read
  // "NaOH; then hydroxide" for one base and "hydroxide; then hydroxide" for
  // none at all. acrossStages does the same for solvent and acid-base.
  const labels: string[] = [];
  for (const stage of reaction.stages) {
    const label = stageReagentLabel(stage);
    if (label.length > 0 && label !== labels[labels.length - 1]) labels.push(label);
  }
  return labels.join("; then ");
}

/**
 * The reagent line with anything already named as a reactant taken out.
 *
 * Three cards printed one species twice in two spellings: the diene card read
 * "buta-1,3-diene + acrolein" over "acrolein", and the amide card "benzoyl
 * chloride + methylamine" over "CH3NH2". The face then shows three things in
 * a flask the data says holds two, and the two spellings of one species are
 * exactly what a tired reader mis-counts. Matching is on the label, loosely,
 * because the two sides of a card name the same species in two registers by
 * design (the bottle wears a formula, the reactant wears a name).
 */
function reagentsBesides(reaction: StagedReaction): string {
  const named = reaction.reactant_labels.map((label) => label.trim().toLowerCase());
  // The same species under its bottle spelling: the reactant SMILES run
  // through the same table the reagent line uses, index-aligned with the
  // labels above, so "methylamine" also catches "CH3NH2".
  const formulae = reaction.reactants
    .map((smiles) => (REAGENT_LABELS[smiles] ?? "").toLowerCase())
    .filter((entry) => entry.length > 0);
  const line = stagedReagentLine(reaction);
  const kept = line
    .split("; then ")
    .filter((part) => {
      const token = part.trim().toLowerCase();
      return token.length > 0 && !named.includes(token) && !formulae.includes(token);
    });
  return kept.join("; then ");
}

/** The first stated temperature across the stages, or null when none is. */
export function stagedTemperature(reaction: StagedReaction): number | null {
  for (const stage of reaction.stages) {
    if (stage.conditions.temperature_c !== null) return stage.conditions.temperature_c;
  }
  return null;
}

/**
 * The selectivity note, when an author wrote one. The generated data keeps
 * 1,2 against 1,4 reasoning inside a stage's `notes`, so the note is carried
 * VERBATIM when it names either addition mode, and no note means no field.
 * A substring test is crude, but the alternative is retyping authored
 * sentences into a second table, which is how two copies drift.
 */
export function stagedSelectivityNote(reaction: StagedReaction): string | null {
  for (const stage of reaction.stages) {
    const note = stage.conditions.notes;
    if (note.includes("1,2") || note.includes("1,4")) return note;
  }
  return null;
}

/**
 * Distinct values across the stages, in stage order, joined the way the
 * sequence reads: "THF, then water". Distinct rather than one per stage
 * because a two stage reaction run in one solvent should say it once.
 */
function acrossStages(values: readonly string[]): string {
  const seen: string[] = [];
  for (const value of values) {
    const trimmed = value.trim();
    if (trimmed.length > 0 && !seen.includes(trimmed)) seen.push(trimmed);
  }
  return seen.join(", then ");
}

/** "THF, then water", from the solvents the stages state. Empty when none do. */
export function stagedSolvent(reaction: StagedReaction): string {
  return acrossStages(reaction.stages.map((stage) => stage.conditions.solvent));
}

/** "basic, then acidic", from the acid_base reading each stage carries. */
export function stagedAcidBase(reaction: StagedReaction): string {
  return acrossStages(reaction.stages.map((stage) => stage.conditions.acid_base));
}

/**
 * The authored notes, which are real teaching sentences and exist on every
 * one of the 43 reactions. Numbered when there is more than one, so a two
 * stage reaction's two sentences do not read as one paragraph; the panel
 * renders them with pre-line, so the newline is the break the student sees.
 *
 * `skip` drops a note that already went out under its own label, so the
 * michael-addition selectivity sentence is not printed twice.
 */
export function stagedNotes(reaction: StagedReaction, skip: string | null): string {
  const notes: string[] = [];
  for (const stage of reaction.stages) {
    const note = stage.conditions.notes.trim();
    if (note.length > 0 && note !== skip && !notes.includes(note)) notes.push(note);
  }
  if (notes.length <= 1) return notes[0] ?? "";
  return notes.map((note, index) => `${index + 1}. ${note}`).join("\n");
}

/** The registry's drawing paths, renamed into the card's own casing. */
function artFrom(reaction: StagedReaction): ReactionCardArt {
  const { start_light, start_dark, product_light, product_dark } = reaction.art;
  return {
    ...(start_light === undefined ? {} : { startLight: start_light }),
    ...(start_dark === undefined ? {} : { startDark: start_dark }),
    ...(product_light === undefined ? {} : { productLight: product_light }),
    ...(product_dark === undefined ? {} : { productDark: product_dark }),
  };
}

/**
 * One authored reaction becomes one reaction card. Every string is the
 * data's own; the reveal carries only what the data states (the selectivity
 * note where one exists, plus the solvent, the acid/base reading and the
 * authored notes, which every reaction has), and front/back/why are populated
 * too so every surface that predates reaction cards renders the card whole,
 * with the same mapping composer.ts already uses: front asks with the
 * starting side, back answers with the product, why carries the conditions.
 */
export function reactionCardFromStaged(reaction: StagedReaction, now: Date): Card {
  const reactants = reaction.reactant_labels.join(" + ");
  const reagents = reagentsBesides(reaction);
  const celsius = stagedTemperature(reaction);
  const selectivity = stagedSelectivityNote(reaction);

  const solvent = stagedSolvent(reaction);
  const acidBase = stagedAcidBase(reaction);
  const notes = stagedNotes(reaction, selectivity);

  const reveal: ReactionReveal = {
    ...(selectivity !== null ? { selectivity } : {}),
    ...(solvent.length > 0 ? { solvent } : {}),
    ...(acidBase.length > 0 ? { acidBase } : {}),
    ...(notes.length > 0 ? { notes } : {}),
  };
  const temperature = celsius === null ? null : temperatureLabel(celsius);
  const art = artFrom(reaction);

  return {
    id: reactionCardId(reaction.id),
    front: reactants,
    back: reaction.product_label,
    why: `Conditions: ${reagents}${temperature === null ? "" : `, ${temperature}`}`,
    tags: [reaction.family],
    source: { kind: "reaction", reactionId: reaction.id, at: now.toISOString() },
    reaction: {
      reactants,
      reagents,
      products: reaction.product_label,
      ...(temperature === null ? {} : { temperature }),
      ...(Object.keys(art).length === 0 ? {} : { art }),
      reveal,
    },
  };
}

/**
 * The card a #/draw save produces, or null when the reaction id resolves to
 * nothing (a stale link). Null is a save not made, never a card with a
 * placeholder in it.
 */
export function drawCardFor(reactionId: string, now: Date): Card | null {
  const reaction = REACTIONS.find((entry) => entry.id === reactionId);
  return reaction === undefined ? null : reactionCardFromStaged(reaction, now);
}
