/**
 * Reaction cards, built from the authored reaction data. Read this header
 * before trusting anything in this file.
 *
 * THE OWNER'S DECISION (17 Sep): the reaction card's front shows reactants
 * plus reagents on one side of the arrow and products on the other, with the
 * temperature on the face; tapping reveals the optional labelled extras (Keq,
 * pKa, 1,2 against 1,4 selectivity, electronegativity, resonance notes).
 *
 * THE CHEMISTRY RULE, and it shapes every function here: chemistry shown to a
 * student is derived from authored data or RDKit, never recalled. Everything
 * this file writes onto a card is lifted VERBATIM out of data/reactions.ts,
 * which is generated by scripts/build_curriculum.py and RDKit-checked. A
 * field the data does not carry (a pKa, a Keq) is left ABSENT rather than
 * filled in from a model's memory, and the face renders only what exists.
 *
 * THE ID IS DERIVED, NEVER MINTED, per cards/types.ts's invariant: the same
 * reaction saved twice, or saved on the draw page and later seeded, is ONE
 * card that keeps its interval history, not two cards with rival schedules.
 *
 * Pure: no storage, no clock reads (now arrives as an argument), no React.
 * The store and the surfaces sit on the other side of this file.
 */

import { REACTIONS, type StagedReaction } from "../../data/reactions";
import type { Card, CardId, ReactionReveal } from "./types";

// The reveal vocabulary (REVEAL_ORDER, REVEAL_LABELS, presentReveal) lives in
// types.ts with the shapes it describes, so the composer can reach it without
// pulling this file's REACTIONS import into its bundle.

/* ------------------------------------------------------------------ */
/* Building a card from one authored reaction                           */
/* ------------------------------------------------------------------ */

/** The stable id. `reaction:` is its own namespace beside `mistake:` etc. */
export function reactionCardId(reactionId: string): CardId {
  return `reaction:${reactionId}`;
}

/** "-78 °C", from the number the data carries. */
export function temperatureLabel(celsius: number): string {
  return `${celsius} °C`;
}

/**
 * "CH3MgBr; then H3O+" from the staged reagents. Each stage's DISPLAY name is
 * its last reagent entry (the data lists the mechanistic species first and
 * the bottle label last), which is the same read ReactionDrawPage used for
 * its card fronts before this module took the job over.
 */
export function stagedReagentLine(reaction: StagedReaction): string {
  return reaction.stages
    .map((s) => s.reagents[s.reagents.length - 1] ?? s.reagents[0] ?? "")
    .filter(Boolean)
    .join("; then ");
}

/** The first stated temperature across the stages, or null when none is. */
export function stagedTemperature(reaction: StagedReaction): number | null {
  for (const stage of reaction.stages) {
    if (stage.conditions.temperature_c !== null) return stage.conditions.temperature_c;
  }
  return null;
}

/**
 * The selectivity note, when an author wrote one. The generated data keeps
 * 1,2 against 1,4 reasoning inside a stage's `notes`, so the note is carried
 * VERBATIM when it names either addition mode, and no note means no field.
 * A substring test is crude, but the alternative is retyping authored
 * sentences into a second table, which is how two copies drift.
 */
export function stagedSelectivityNote(reaction: StagedReaction): string | null {
  for (const stage of reaction.stages) {
    const note = stage.conditions.notes;
    if (note.includes("1,2") || note.includes("1,4")) return note;
  }
  return null;
}

/**
 * One authored reaction becomes one reaction card. Every string is the
 * data's own; the reveal carries only what the data states (today that is
 * the selectivity note, where one exists), and front/back/why are populated
 * too so every surface that predates reaction cards renders the card whole,
 * with the same mapping composer.ts already uses: front asks with the
 * starting side, back answers with the product, why carries the conditions.
 */
export function reactionCardFromStaged(reaction: StagedReaction, now: Date): Card {
  const reactants = reaction.reactant_labels.join(" + ");
  const reagents = stagedReagentLine(reaction);
  const celsius = stagedTemperature(reaction);
  const selectivity = stagedSelectivityNote(reaction);

  const reveal: ReactionReveal = {
    ...(selectivity !== null ? { selectivity } : {}),
  };
  const temperature = celsius === null ? null : temperatureLabel(celsius);

  return {
    id: reactionCardId(reaction.id),
    front: reactants,
    back: reaction.product_label,
    why: `Conditions: ${reagents}${temperature === null ? "" : `, ${temperature}`}`,
    tags: [reaction.family],
    source: { kind: "reaction", reactionId: reaction.id, at: now.toISOString() },
    reaction: {
      reactants,
      reagents,
      products: reaction.product_label,
      ...(temperature === null ? {} : { temperature }),
      reveal,
    },
  };
}

/**
 * The card a #/draw save produces, or null when the reaction id resolves to
 * nothing (a stale link). Null is a save not made, never a card with a
 * placeholder in it.
 */
export function drawCardFor(reactionId: string, now: Date): Card | null {
  const reaction = REACTIONS.find((entry) => entry.id === reactionId);
  return reaction === undefined ? null : reactionCardFromStaged(reaction, now);
}
