import type { StudyDeck } from "@/data/types";

/**
 * Acetals, imines and enamines — 13 cards.
 *
 * Generated by scripts/make_flashcards.py in the mechanism_trainer repo. Do not
 * hand edit: the next run overwrites it, and the point of generating it is that
 * a card cannot drift from the reaction page it came from.
 */
export const carbonylCatalysisDeck: StudyDeck = {
  id: "carbonyl-catalysis",
  title: "Acetals, imines and enamines",
  short: "Acetals & imines",
  group: "carbonyls",
  titleLines: ["ACETALS", "AND IMINES"],
  subtitle: "All reversible, all acid catalysed, and all the same first four steps.",
  blurb: "All reversible, all acid catalysed, and all the same first four steps.",
  about: "Protonate the carbonyl, nucleophile on, proton shuffle, lose water. Four steps, and they are the same four whether the nucleophile is an alcohol or an amine.\n\nWhat differs is what happens next. Two alcohols get you an acetal, a primary amine gets an imine, a secondary amine cannot form the C=N so it forms the enamine instead.\n\nEvery one of them is reversible, which is what makes acetals useful as protecting groups: put it on with the water removed, take it off with water in excess. The pH window matters too — too acidic and the amine is protonated and is no longer a nucleophile at all, which is why imine formation runs at pH 4-5 rather than in strong acid.",
  motif: "chalcone",
  art: "cover_catalysis.svg",
  from: "#a21caf",
  to: "#d946ef",
  questions: [
    { q: "Protecting a ketone as an acetal: Acetophenone + HOCH₂CH₂OH , TsOH cat. , benzene, −H₂O (Dean–Stark)", a: "acidic  ·  reversible  ·  Reflux, with water removed", badge: "Cyclic acetal", image: "carbonyl_acetal-on.svg", imageCrop: "37%", heading: "Acetals, imines and enamines · worked examples" },
    { q: "Removing an acetal: Cyclic acetal + H₃O⁺ , excess H₂O", a: "acidic  ·  reversible  ·  Room temperature, aqueous", badge: "Acetophenone", image: "carbonyl_acetal-off.svg", imageCrop: "37%", heading: "Acetals, imines and enamines · worked examples" },
    { q: "Protecting a ketone as a dimethyl ketal: Acetophenone + 2 CH₃OH , H⁺ cat., −H₂O", a: "acidic  ·  reversible  ·  Reflux, water removed", badge: "Dimethyl ketal", image: "carbonyl_acetal-ome.svg", imageCrop: "37%", heading: "Acetals, imines and enamines · worked examples" },
    { q: "Imine from an aldehyde and a primary amine: Benzaldehyde + CH₃NH₂ , H⁺ cat., pH 4-5", a: "acidic  ·  reversible  ·  Room temperature", badge: "N-methylbenzaldimine", image: "carbonyl_imine.svg", imageCrop: "37%", heading: "Acetals, imines and enamines · worked examples" },
    { q: "Enamine from a symmetric ketone: Cyclohexanone + pyrrolidine , H⁺ cat., −H₂O", a: "acidic  ·  reversible  ·  Reflux, water removed", badge: "1-pyrrolidinocyclohexene", image: "carbonyl_enamine-sym.svg", imageCrop: "37%", heading: "Acetals, imines and enamines · worked examples" },
    { q: "Enamine from an asymmetric ketone: 2-methylcyclohexanone + pyrrolidine , H⁺ cat., −H₂O", a: "acidic  ·  reversible  ·  Reflux, water removed", badge: "Less substituted enamine", image: "carbonyl_enamine-asym.svg", imageCrop: "37%", heading: "Acetals, imines and enamines · worked examples" },
    { q: "Alkylation of an enamine: 1-pyrrolidinocyclohexene + CH₃I , then H₂O", a: "neutral  ·  irreversible  ·  Room temperature, then aqueous workup", badge: "2-methylcyclohexanone", image: "carbonyl_enamine-alkylation.svg", imageCrop: "37%", heading: "Acetals, imines and enamines · worked examples" },
    { q: "Protecting a carbonyl as an acetal of cyclohexanone: Cyclohexanone + HOCH₂CH₂OH , TsOH cat. , benzene, −H₂O (Dean–Stark)", a: "acidic  ·  reversible  ·  Reflux, with water removed", badge: "Cyclohexanone ethylene acetal", image: "carbonyl_var_acetal-on_0.svg", imageCrop: "37%", heading: "Acetals, imines and enamines · more of the same" },
    { q: "Protecting a carbonyl as an acetal of benzaldehyde: Benzaldehyde + HOCH₂CH₂OH , TsOH cat. , benzene, −H₂O (Dean–Stark)", a: "acidic  ·  reversible  ·  Reflux, with water removed", badge: "Benzaldehyde ethylene acetal", image: "carbonyl_var_acetal-on_1.svg", imageCrop: "37%", heading: "Acetals, imines and enamines · more of the same" },
    { q: "Protecting a carbonyl as an acetal of butan-2-one: Butan-2-one + HOCH₂CH₂OH , TsOH cat. , benzene, −H₂O (Dean–Stark)", a: "acidic  ·  reversible  ·  Reflux, with water removed", badge: "Butan-2-one ethylene acetal", image: "carbonyl_var_acetal-on_2.svg", imageCrop: "37%", heading: "Acetals, imines and enamines · more of the same" },
    { q: "Imine from a carbonyl and a primary amine of cyclohexanone: Cyclohexanone + CH₃NH₂ , H⁺ cat. , pH 4–5, −H₂O", a: "acidic  ·  reversible  ·  Room temperature", badge: "N-Methylcyclohexanimine", image: "carbonyl_var_imine_3.svg", imageCrop: "37%", heading: "Acetals, imines and enamines · more of the same" },
    { q: "Imine from a carbonyl and a primary amine of 4-Chlorobenzaldehyde: 4-Chlorobenzaldehyde + CH₃NH₂ , H⁺ cat. , pH 4–5, −H₂O", a: "acidic  ·  reversible  ·  Room temperature", badge: "N-Methyl-4-chlorobenzaldimine", image: "carbonyl_var_imine_4.svg", imageCrop: "37%", heading: "Acetals, imines and enamines · more of the same" },
    { q: "Imine from a carbonyl and a primary amine of propanal: Propanal + CH₃NH₂ , H⁺ cat. , pH 4–5, −H₂O", a: "acidic  ·  reversible  ·  Room temperature", badge: "N-Methylpropanimine", image: "carbonyl_var_imine_5.svg", imageCrop: "37%", heading: "Acetals, imines and enamines · more of the same" },
  ],
};
