import type { ReferenceDeck } from "@/data/types";
import { carbonylAdditionDeck } from "./addition";
import { carbonylAcylSubstitutionDeck } from "./acyl-substitution";
import { carbonylReductionDeck } from "./reduction";
import { carbonylAcidsDeck } from "./acids";
import { carbonylOxidationDeck } from "./oxidation";
import { carbonylCatalysisDeck } from "./catalysis";
import { carbonylReagentsDeck } from "./reagents";
import { carbonylRetroDeck } from "./retro";
import { carbonylNameReagentDeck } from "./name-reagent";

/**
 * The Carbonyls folder: one deck per reaction type, then the same reactions
 * asked backwards.
 *
 * Generated by scripts/make_flashcards.py in the mechanism_trainer repo,
 * including this file. Adding a reaction family there adds a deck here.
 */
export const carbonylDecks: ReferenceDeck[] = [
  carbonylAdditionDeck,
  carbonylAcylSubstitutionDeck,
  carbonylReductionDeck,
  carbonylAcidsDeck,
  carbonylOxidationDeck,
  carbonylCatalysisDeck,
  carbonylReagentsDeck,
  carbonylRetroDeck,
  carbonylNameReagentDeck,
];
