import type { StudyDeck } from "@/data/types";
import { carbonylAdditionDeck } from "./addition";
import { carbonylAcylSubstitutionDeck } from "./acyl-substitution";
import { carbonylReductionDeck } from "./reduction";
import { carbonylAcidsDeck } from "./acids";
import { carbonylOxidationDeck } from "./oxidation";
import { carbonylCatalysisDeck } from "./catalysis";
import { carbonylReagentsDeck } from "./reagents";
import { carbonylRetroDeck } from "./retro";
import { carbonylNameReagentDeck } from "./name-reagent";
import { carbonylAllDeck } from "./all";

/**
 * The Carbonyls folder: one deck per reaction type, the same reactions asked
 * backwards and as reagent questions, then all of them together.
 *
 * These are study decks rather than reference decks. They were reference decks
 * because their cards are pictures, which cost them ratings, progress and every
 * view mode for no reason — a card carrying an image is still a card.
 *
 * Generated by scripts/make_flashcards.py in the mechanism_trainer repo,
 * including this file. Adding a reaction family there adds a deck here.
 */
export const carbonylDecks: StudyDeck[] = [
  carbonylAdditionDeck,
  carbonylAcylSubstitutionDeck,
  carbonylReductionDeck,
  carbonylAcidsDeck,
  carbonylOxidationDeck,
  carbonylCatalysisDeck,
  carbonylReagentsDeck,
  carbonylRetroDeck,
  carbonylNameReagentDeck,
  carbonylAllDeck,
];
