import type { StudyDeck } from "@/data/types";

/**
 * Making the reagents — 2 cards.
 *
 * Generated by scripts/make_flashcards.py in the mechanism_trainer repo. Do not
 * hand edit: the next run overwrites it, and the point of generating it is that
 * a card cannot drift from the reaction page it came from.
 */
export const carbonylReagentsDeck: StudyDeck = {
  id: "carbonyl-reagents",
  title: "Making the reagents",
  short: "Reagents",
  group: "carbonyls",
  titleLines: ["MAKING THE", "REAGENTS"],
  subtitle: "The things the reactions in the other decks assume you already have.",
  blurb: "The things the reactions in the other decks assume you already have.",
  about: "Two reactions that are not about carbonyls at all, and are here because every other deck in this folder quietly assumes you can make what it hands you.\n\nFriedel-Crafts acylation is where the aryl ketones come from, and the ylide is what the Wittig needs before it can do anything.",
  motif: "benzene",
  from: "#c026d3",
  to: "#e879f9",
  questions: [
    { q: "Friedel-Crafts acylation: Benzene + CH₃COCl , AlCl₃", a: "anhydrous  ·  irreversible  ·  0 °C to room temperature", badge: "Acetophenone", image: "carbonyl_friedel-crafts.svg", imageCrop: "37%", heading: "Making the reagents · worked examples" },
    { q: "Making a phosphonium ylide: Triphenylphosphine + CH₃Br , then n-BuLi", a: "anhydrous  ·  irreversible  ·  0 °C, under nitrogen", badge: "Methylenetriphenylphosphorane", image: "carbonyl_ylide.svg", imageCrop: "37%", heading: "Making the reagents · worked examples" },
  ],
};
