import type { StudyDeck } from "@/data/types";

/**
 * Reduction — 13 cards.
 *
 * Generated by scripts/make_flashcards.py in the mechanism_trainer repo. Do not
 * hand edit: the next run overwrites it, and the point of generating it is that
 * a card cannot drift from the reaction page it came from.
 */
export const carbonylReductionDeck: StudyDeck = {
  id: "carbonyl-reduction",
  title: "Reduction",
  short: "Reduction",
  group: "carbonyls",
  titleLines: ["CARBONYL", "REDUCTION"],
  subtitle: "Hydride in, or the C=O taken off the molecule altogether.",
  blurb: "Hydride in, or the C=O taken off the molecule altogether.",
  about: "Two different questions wearing the same word.\n\nHydride reagents add H⁻ to the carbonyl carbon, and which one you use decides how far it goes: NaBH₄ will not touch an ester, LiAlH₄ takes it all the way to the alcohol, and DIBAL-H at −78 °C stops at the aldehyde. The temperature is not decoration on that last one, it is the answer.\n\nClemmensen and Wolff–Kishner are the other kind: they do not add anything, they remove the oxygen and leave a CH₂. One is acidic and one is basic, which is how you choose between them when the rest of the molecule cannot survive both.",
  motif: "reflux",
  art: "cover_reduction.svg",
  from: "#6d28d9",
  to: "#8b5cf6",
  questions: [
    { q: "LiAlH₄ on an ester: Methyl benzoate + LiAlH₄ (excess) , Et₂O; then H₃O⁺", a: "anhydrous  ·  irreversible  ·  0 °C to room temperature, then acidic workup", badge: "Benzyl alcohol", image: "carbonyl_lialh4-ester.svg", imageCrop: "37%", heading: "Reduction · worked examples" },
    { q: "DIBAL-H on an ester: Methyl benzoate + DIBAL-H (1 eq) , toluene, −78 °C; then H₃O⁺", a: "anhydrous  ·  irreversible  ·  −78 °C, then acidic workup", badge: "Benzaldehyde", image: "carbonyl_dibal.svg", imageCrop: "37%", heading: "Reduction · worked examples" },
    { q: "Wolff–Kishner reduction: Acetophenone + H₂NNH₂ , KOH , diethylene glycol, Δ", a: "basic  ·  irreversible  ·  180–200 °C in a high-boiling solvent", badge: "Ethylbenzene", image: "carbonyl_wolff-kishner.svg", imageCrop: "37%", heading: "Reduction · worked examples" },
    { q: "Clemmensen reduction: Acetophenone + Zn(Hg) , conc. HCl, Δ", a: "acidic  ·  irreversible  ·  Reflux in concentrated HCl", badge: "Ethylbenzene", image: "carbonyl_clemmensen.svg", imageCrop: "37%", heading: "Reduction · worked examples" },
    { q: "LiAlH₄ on an ester of methyl propanoate: Methyl propanoate + LiAlH₄ (excess) , then H₃O⁺ , Et₂O, anhydrous", a: "anhydrous  ·  irreversible  ·  0 °C to room temperature, then acidic workup", badge: "Propan-1-ol", image: "carbonyl_var_lialh4-ester_0.svg", imageCrop: "37%", heading: "Reduction · more of the same" },
    { q: "LiAlH₄ on an ester of methyl 4-methoxybenzoate: Methyl 4-methoxybenzoate + LiAlH₄ (excess) , then H₃O⁺ , Et₂O, anhydrous", a: "anhydrous  ·  irreversible  ·  0 °C to room temperature, then acidic workup", badge: "4-Methoxybenzyl alcohol", image: "carbonyl_var_lialh4-ester_1.svg", imageCrop: "37%", heading: "Reduction · more of the same" },
    { q: "LiAlH₄ on an ester of ethyl butanoate: Ethyl butanoate + LiAlH₄ (excess) , then H₃O⁺ , Et₂O, anhydrous", a: "anhydrous  ·  irreversible  ·  0 °C to room temperature, then acidic workup", badge: "Butan-1-ol", image: "carbonyl_var_lialh4-ester_2.svg", imageCrop: "37%", heading: "Reduction · more of the same" },
    { q: "DIBAL-H on an ester of ethyl butanoate: Ethyl butanoate + DIBAL-H (1 eq) , then H₃O⁺ , toluene, −78 °C", a: "anhydrous  ·  irreversible  ·  −78 °C, then acidic workup", badge: "Butanal", image: "carbonyl_var_dibal_3.svg", imageCrop: "37%", heading: "Reduction · more of the same" },
    { q: "DIBAL-H on an ester of methyl 4-chlorobenzoate: Methyl 4-chlorobenzoate + DIBAL-H (1 eq) , then H₃O⁺ , toluene, −78 °C", a: "anhydrous  ·  irreversible  ·  −78 °C, then acidic workup", badge: "4-Chlorobenzaldehyde", image: "carbonyl_var_dibal_4.svg", imageCrop: "37%", heading: "Reduction · more of the same" },
    { q: "DIBAL-H on an ester of ethyl acetate: Ethyl acetate + DIBAL-H (1 eq) , then H₃O⁺ , toluene, −78 °C", a: "anhydrous  ·  irreversible  ·  −78 °C, then acidic workup", badge: "Acetaldehyde", image: "carbonyl_var_dibal_5.svg", imageCrop: "37%", heading: "Reduction · more of the same" },
    { q: "Clemmensen reduction of propiophenone: Propiophenone + Zn(Hg) , conc. HCl, Δ", a: "acidic  ·  irreversible  ·  Reflux in concentrated HCl", badge: "Propylbenzene", image: "carbonyl_var_clemmensen_6.svg", imageCrop: "37%", heading: "Reduction · more of the same" },
    { q: "Clemmensen reduction of cyclohexanone: Cyclohexanone + Zn(Hg) , conc. HCl, Δ", a: "acidic  ·  irreversible  ·  Reflux in concentrated HCl", badge: "Cyclohexane", image: "carbonyl_var_clemmensen_7.svg", imageCrop: "37%", heading: "Reduction · more of the same" },
    { q: "Clemmensen reduction of 4′-Methylacetophenone: 4′-Methylacetophenone + Zn(Hg) , conc. HCl, Δ", a: "acidic  ·  irreversible  ·  Reflux in concentrated HCl", badge: "4-Ethyltoluene", image: "carbonyl_var_clemmensen_8.svg", imageCrop: "37%", heading: "Reduction · more of the same" },
  ],
};
