import { useState } from "react";
import { ArrowRight, BookOpen, ChevronLeft, FlaskConical, Layers, Sparkles } from "lucide-react";
import { Blueberry } from "@/components/ui/blueberry";
import { SiteFooter } from "@/components/ui/site-footer";
import { PageBackground } from "@/components/ui/page-background";
import { LessonVideo } from "@/components/ui/lesson-video";
import { LessonSidebar } from "@/components/ui/lesson-sidebar";
type T={id:string;label:string;title:string;lead:string;mechanism:string;difference:string;deck:string;examples:string[][]};
/**
 * Stand-in thumbnails for the template video, one per section.
 *
 * Reusing the background photographs rather than adding seven more files: these
 * are placeholders, and shipping real artwork for a video that does not exist
 * is work that gets thrown away.
 */
const POSTERS:Record<string,string>={overview:"forest-misty-forest.webp",addition:"forest-river-through-dense-forest.webp",substitution:"forest-rainforest-waterfall.webp",oxidation:"forest-clouds-through-the-forest.webp",reduction:"forest-little-forest.webp",protection:"forest-water-dripping-from-leaves.webp",enolate:"forest-nature.webp"};
const topics:T[]=[
{id:"overview",label:"Overview",title:"Read the carbonyl before choosing a reagent.",lead:"A nucleophile attacks the electron-poor carbonyl carbon and the pi electrons move to oxygen.",mechanism:"Aldehydes and ketones add and stop because nothing can leave. Acid derivatives add, then eliminate a leaving group through a tetrahedral intermediate.",difference:"Ask first: add and stop, or add then eliminate?",deck:"carbonyl-all",examples:[["NaBH4 on acetophenone","MeOH | 0 C to room temperature","1-Phenylethanol","carbonyl_nabh4-ketone.svg"],["Gilman on benzoyl chloride","Me2CuLi | Et2O | -78 C","Acetophenone","carbonyl_gilman.svg"]]},
{id:"addition",label:"Addition",title:"Nucleophilic addition: the new group stays.",lead:"A nucleophile goes onto the carbonyl carbon and oxygen becomes an alkoxide. It stops because nothing on that carbon can leave.",mechanism:"Hydride, cyanide, acetylide, Grignard reagent, and water make the same opening move. The alkoxide then needs a proton source, so acidic workup is a real step.",difference:"The reagent decides the group added; the substrate decides the alcohol class.",deck:"carbonyl-addition",examples:[["Cyanohydrin formation","NaCN | H2O | pH about 10","Acetone cyanohydrin","carbonyl_cyanohydrin.svg"],["Wittig olefination","Ph3P=CH2 | THF","Styrene","carbonyl_wittig.svg"],["Grignard addition","CH3MgBr; then H3O+","1-Phenylethanol","carbonyl_var_grignard-add_8.svg"]]},
{id:"substitution",label:"Acyl substitution",title:"Same opening move. Different second half.",lead:"A nucleophile adds to an acid derivative, then oxygen comes back down and pushes a leaving group out.",mechanism:"This is addition then elimination through a tetrahedral intermediate. Reactivity follows leaving-group ability: acid chloride, anhydride, ester, then amide.",difference:"A chloride, ester oxygen, or anhydride group can leave; that is why this substitutes.",deck:"carbonyl-acyl-substitution",examples:[["Acetylation of vanillin","Ac2O | NaOH | H2O","Vanillin acetate","carbonyl_vanillin-acetylation.svg"],["Anhydride formation","Acetyl chloride | acetate | pyridine","Acetic anhydride","carbonyl_anhydride.svg"],["Nitrile hydrolysis","H3O+ | heat","Benzoic acid","carbonyl_nitrile-acidic.svg"]]},
{id:"reduction",label:"Reduction",title:"Hydride adds; conditions decide where it stops.",lead:"NaBH4 is gentle, LiAlH4 takes esters to alcohols, and DIBAL-H at -78 C stops at an aldehyde.",mechanism:"Hydride addition makes an alkoxide that is protonated during workup. Clemmensen and Wolff-Kishner instead remove the carbonyl oxygen entirely to make CH2.",difference:"Temperature is part of the answer for DIBAL-H.",deck:"carbonyl-reduction",examples:[["Ester to alcohol","LiAlH4; then H3O+","Benzyl alcohol","carbonyl_lialh4-ester.svg"],["Ester to aldehyde","DIBAL-H | -78 C; then H3O+","Benzaldehyde","carbonyl_dibal.svg"],["Carbonyl to CH2","Zn(Hg) | conc. HCl | heat","Ethylbenzene","carbonyl_clemmensen.svg"]]},
{id:"oxidation",label:"Oxidation",title:"Water decides whether a primary alcohol keeps going.",lead:"A secondary alcohol oxidizes to a ketone. A primary alcohol gives an aldehyde with PCC or a carboxylic acid with Jones.",mechanism:"PCC is anhydrous, so it stops at the aldehyde. Jones is aqueous: the aldehyde hydrates and is oxidized again.",difference:"PCC versus Jones follows from whether water is present.",deck:"carbonyl-oxidation",examples:[["Primary alcohol to aldehyde","PCC | CH2Cl2 | anhydrous","Benzaldehyde","carbonyl_pcc.svg"],["Primary alcohol to acid","CrO3 | H2SO4 | H2O","Benzoic acid","carbonyl_jones-primary.svg"],["Secondary alcohol to ketone","CrO3 | H2SO4 | H2O","Acetone","carbonyl_jones.svg"]]},
{id:"nitrogen",label:"Nitrogen",title:"An amine attacks; the final proton determines the product.",lead:"Primary amines form imines. Secondary amines form enamines because the iminium must lose a proton from carbon, not nitrogen.",mechanism:"An amine adds, proton transfers make water into a leaving group, water leaves, and the iminium loses its final proton. Every step is reversible under aqueous acid.",difference:"Enamines make the alpha carbon nucleophilic without directly making an enolate.",deck:"carbonyl-catalysis",examples:[["Imine formation","Primary amine | H+ cat. | pH 4-5","N-Methyl benzaldimine","carbonyl_imine.svg"],["Enamine alkylation","Pyrrolidine; then RX; then H3O+","alpha-Alkylated ketone","carbonyl_enamine-alkylation.svg"]]},
{id:"cycles",label:"Cycles & acids",title:"Make a ring, protect a carbonyl, or follow the acyl map.",lead:"Alcohol addition gives hemiacetals and, under acid, acetals. An internal alcohol can attack its own carbonyl to make the cyclic hemiacetal found in Haworth projections.",mechanism:"Carboxylic acids are poor electrophiles because OH is a poor leaving group. Convert them to a more reactive derivative before acyl substitution.",difference:"Fischer-to-Haworth makes a C-O bond; enolate chemistry makes a C-C bond.",deck:"carbonyl-acids",examples:[["Cyclic hemiacetal","H+ cat. | intramolecular","Cyclic hemiacetal","carbonyl_cyclic-hemiacetal.svg"],["Fischer esterification","ROH | H+ cat. | remove water","Ester","carbonyl_fischer.svg"],["Acid to acid chloride","SOCl2 | pyridine","Acid chloride","carbonyl_socl2.svg"]]}
];
export function LessonsPage(){const [active,setActive]=useState("overview");const t=topics.find(x=>x.id===active)||topics[0];return <main className="relative min-h-screen text-slate-900 dark:text-stone-100"><PageBackground /><div className="mx-auto max-w-7xl px-4 py-5 sm:px-6 lg:px-8"><a href="#/home" className="inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-slate-600 hover:text-indigo-700 dark:text-stone-300"><ChevronLeft className="size-4"/>Home</a><header className="mt-5 grid gap-5 rounded-3xl border border-indigo-200/80 bg-white/75 p-6 shadow-sm dark:border-indigo-400/20 dark:bg-stone-950/70 lg:grid-cols-[1fr_270px]"><div><p className="font-mono text-xs font-semibold uppercase tracking-[.18em] text-indigo-600 dark:text-indigo-300">Lessons / Organic chemistry II</p><h1 className="title-face mt-3 text-5xl leading-none">Carbonyls</h1><p className="mt-4 max-w-2xl leading-7 text-slate-600 dark:text-stone-300">A board for the ideas behind the cards: recognize the functional group, choose the pathway, then practice concrete examples.</p></div>{/* The berry reads along with you. `reading` looks down at the page rather
    than out at the room, which is the difference between a mascot that is
    keeping you company and one that is watching you. */}
<div className="flex flex-col items-center justify-center rounded-2xl border border-dashed border-indigo-300 bg-indigo-50/70 p-4 dark:border-indigo-400/30 dark:bg-indigo-950/25"><Blueberry mood="reading" interactive onActivate={()=>{window.location.hash="#/home";}} className="h-40 w-40" label="Blueberry, reading along. Press to go home, drag to spin."/><p className="mt-2 text-center text-sm text-indigo-900/75 dark:text-indigo-100/75">Seven sections. Start with the overview if the carbonyl still looks like one reaction.</p></div></header>{/* Sidebar and content, rather than a row of pills over a single column.

    Seven pills was already a scrolling strip on a laptop, and it gives no sense
    of where a section sits in the whole. A list down the side shows the shape of
    the subject at a glance and has room for the ones still to be written. On
    narrow screens the sidebar becomes a single dropdown, since a fixed column
    on a phone is most of the screen. */}
<div className="mt-5 grid items-start gap-5 lg:grid-cols-[240px_1fr]">
<LessonSidebar topics={topics.map(x=>({id:x.id,label:x.label}))} active={active} onSelect={setActive}/>
<div className="min-w-0">
<section className="grid gap-5 xl:grid-cols-[1fr_290px]"><article className="rounded-3xl border border-slate-200 bg-white/80 p-6 shadow-sm dark:border-stone-800 dark:bg-stone-950/70 sm:p-8"><LessonVideo title={t.title} poster={POSTERS[t.id]||"forest-misty-forest.webp"} className="mb-6"/><p className="font-mono text-xs font-semibold uppercase tracking-[.16em] text-fuchsia-700 dark:text-fuchsia-300">{t.label}</p><h2 className="title-face mt-3 text-4xl leading-tight">{t.title}</h2><p className="mt-5 max-w-3xl leading-7 text-slate-600 dark:text-stone-300">{t.lead}</p><div className="mt-6 grid gap-4 md:grid-cols-2"><Info title="Mechanism" icon={<FlaskConical className="size-4"/>}>{t.mechanism}</Info><Info title="What to distinguish" icon={<Sparkles className="size-4"/>}>{t.difference}</Info></div></article><aside className="rounded-3xl border border-slate-200 bg-white/80 p-5 shadow-sm dark:border-stone-800 dark:bg-stone-950/70"><BookOpen className="size-5 text-indigo-600 dark:text-indigo-300"/><h3 className="mt-3 font-semibold">Practice this section</h3><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-stone-300">The matching deck uses these examples as flashcards.</p><a href={"#/deck/"+t.deck} className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-xl bg-gradient-to-r from-indigo-600 to-fuchsia-600 px-4 text-sm font-semibold text-white"><Layers className="size-4"/>Open study deck <ArrowRight className="size-4"/></a></aside></section><section className="mt-5"><p className="font-mono text-xs font-semibold uppercase tracking-[.16em] text-slate-500 dark:text-stone-400">Worked examples</p><h2 className="title-face mt-1 text-2xl">Products and conditions</h2><div className="mt-3 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{t.examples.map(([a,b,c,d])=><article key={a} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-stone-800 dark:bg-stone-950"><div className="flex h-36 items-center justify-center bg-gradient-to-br from-indigo-50 via-white to-fuchsia-50 p-3 dark:from-indigo-950/35 dark:via-stone-950 dark:to-fuchsia-950/20"><img src={`${import.meta.env.BASE_URL}cards/${d}`} alt={"Product: "+c} className="h-full w-full object-contain" loading="lazy"/></div><div className="p-4"><h3 className="text-sm font-semibold">{a}</h3><p className="mt-1 font-mono text-[.7rem] leading-5 text-indigo-700 dark:text-indigo-300">{b}</p><p className="mt-3 text-sm text-slate-600 dark:text-stone-300"><b>Product:</b> {c}</p></div></article>)}</div></section></div></div></div><SiteFooter/></main>}
function Info({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <div className="rounded-2xl border border-slate-200 bg-slate-50/80 p-4 dark:border-stone-800 dark:bg-stone-900/70"><div className="flex items-center gap-2 text-sm font-semibold text-indigo-700 dark:text-indigo-300">{icon}{title}</div><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-stone-300">{children}</p></div>}
