// GENERATED by scripts/build_curriculum.py. Do not edit by hand.
//
// Every reaction here passed RDKit parse, valence and conservation checks,
// and its claimed reaction_type was fact-checked against Rxn-INSIGHT.
// Reactions that failed any check are NOT here; they are in
// flagged_reactions.json awaiting human review.
//
// Conditions are staged. A hydride reduction is stage 1 (hydride, basic)
// then stage 2 (aqueous acid workup). They never collapse into one label,
// because that is what produced 'NaBH4, acidic conditions'.
//
// Source: CHEM241 Summer II 2026 syllabus and course whiteboards.

export interface StageConditions {
  temperature_c: number | null;
  solvent: string;
  acid_base: "neutral" | "acidic" | "basic";
  notes: string;
}

export interface Stage {
  order: number;
  role: "reagent" | "workup" | "catalyst";
  reagents: string[];
  conditions: StageConditions;
  byproducts: string[];
}

export interface Validation {
  status: "ok" | "flagged";
  checks: Record<string, string>;
  problems: string[];
  classifier_label?: string;
}

export interface StagedReaction {
  id: string;
  name: string;
  family: string;
  tier: number;
  reactants: string[];
  reactant_labels: string[];
  stages: Stage[];
  intermediates: string[];
  product: string;
  product_label: string;
  reaction_type: string;
  reversible: boolean;
  committed_step_index: number | null;
  provenance: "syllabus" | "professor-slide" | "ta-verified" | "ai-proposed";
  validation: Validation;
  balance_lhs: string[];
  balance_rhs: string[];
  redox: boolean;
  /** Paths under BASE_URL. Rendered by RDKit from the canonical SMILES. */
  art: {
    start_light?: string;
    start_dark?: string;
    product_light?: string;
    product_dark?: string;
  };
}

const DATA: { pkaLeavingGroupCutoff: number; reactions: StagedReaction[] } =
{
  "pkaLeavingGroupCutoff": 20.0,
  "reactions": [
    {
      "id": "grignard-addition-ketone",
      "name": "Grignard addition to a ketone",
      "family": "carbonyls/addition",
      "tier": 1,
      "reactants": [
        "CC(=O)c1ccccc1"
      ],
      "reactant_labels": [
        "acetophenone"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "[CH3-]",
            "CH3MgBr"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "THF",
            "acid_base": "basic",
            "notes": "Strictly anhydrous. A Grignard is basic enough to be quenched by any O-H before it reaches the carbonyl."
          },
          "byproducts": []
        },
        {
          "order": 2,
          "role": "workup",
          "reagents": [
            "[H3O+]"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "water",
            "acid_base": "acidic",
            "notes": "Separate step. The reduction itself is not acidic."
          },
          "byproducts": []
        }
      ],
      "intermediates": [
        "CC(C)([O-])c1ccccc1"
      ],
      "product": "CC(C)(O)c1ccccc1",
      "product_label": "2-phenylpropan-2-ol",
      "reaction_type": "nucleophilic addition",
      "reversible": false,
      "committed_step_index": 1,
      "provenance": "professor-slide",
      "balance_lhs": [
        "CC(=O)c1ccccc1",
        "[CH3-]",
        "[H+]"
      ],
      "balance_rhs": [
        "CC(C)(O)c1ccccc1"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "unavailable (classifier has no opinion (OtherReaction))"
        },
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/grignard-addition-ketone-start-light.svg",
        "start_dark": "reactions/grignard-addition-ketone-start-dark.svg",
        "product_light": "reactions/grignard-addition-ketone-product-light.svg",
        "product_dark": "reactions/grignard-addition-ketone-product-dark.svg"
      }
    },
    {
      "id": "cyanohydrin",
      "name": "Cyanohydrin formation",
      "family": "carbonyls/addition",
      "tier": 1,
      "reactants": [
        "O=Cc1ccccc1"
      ],
      "reactant_labels": [
        "benzaldehyde"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "[C-]#N",
            "NaCN"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "",
            "acid_base": "basic",
            "notes": "Modelled as HCN for balance; in practice NaCN then acid."
          },
          "byproducts": []
        }
      ],
      "intermediates": [],
      "product": "N#CC(O)c1ccccc1",
      "product_label": "mandelonitrile",
      "reaction_type": "nucleophilic addition",
      "reversible": true,
      "committed_step_index": null,
      "provenance": "professor-slide",
      "balance_lhs": [
        "O=Cc1ccccc1",
        "C#N"
      ],
      "balance_rhs": [
        "N#CC(O)c1ccccc1"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "unavailable (classifier has no opinion (OtherReaction))"
        },
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/cyanohydrin-start-light.svg",
        "start_dark": "reactions/cyanohydrin-start-dark.svg",
        "product_light": "reactions/cyanohydrin-product-light.svg",
        "product_dark": "reactions/cyanohydrin-product-dark.svg"
      }
    },
    {
      "id": "acetylide-addition",
      "name": "Acetylide addition to an aldehyde",
      "family": "carbonyls/addition",
      "tier": 1,
      "reactants": [
        "O=Cc1ccccc1"
      ],
      "reactant_labels": [
        "benzaldehyde"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "CC#[C-]"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "THF",
            "acid_base": "basic",
            "notes": "Acetylide from terminal alkyne plus NaNH2."
          },
          "byproducts": []
        },
        {
          "order": 2,
          "role": "workup",
          "reagents": [
            "[H3O+]"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "water",
            "acid_base": "acidic",
            "notes": "Separate step. The reduction itself is not acidic."
          },
          "byproducts": []
        }
      ],
      "intermediates": [
        "CC#CC([O-])c1ccccc1"
      ],
      "product": "CC#CC(O)c1ccccc1",
      "product_label": "propargylic alcohol",
      "reaction_type": "nucleophilic addition",
      "reversible": false,
      "committed_step_index": 1,
      "provenance": "professor-slide",
      "balance_lhs": [
        "O=Cc1ccccc1",
        "CC#[C-]",
        "[H+]"
      ],
      "balance_rhs": [
        "CC#CC(O)c1ccccc1"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "unavailable (classifier has no opinion (OtherReaction))"
        },
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/acetylide-addition-start-light.svg",
        "start_dark": "reactions/acetylide-addition-start-dark.svg",
        "product_light": "reactions/acetylide-addition-product-light.svg",
        "product_dark": "reactions/acetylide-addition-product-dark.svg"
      }
    },
    {
      "id": "wittig-olefination",
      "name": "Wittig olefination",
      "family": "carbonyls/addition",
      "tier": 1,
      "reactants": [
        "CC(=O)c1ccccc1"
      ],
      "reactant_labels": [
        "acetophenone"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "[CH2-][P+](c1ccccc1)(c1ccccc1)c1ccccc1"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "THF",
            "acid_base": "basic",
            "notes": "Ylide from CH3-PPh3+ deprotonated by R-Li."
          },
          "byproducts": [
            "O=P(c1ccccc1)(c1ccccc1)c1ccccc1"
          ]
        }
      ],
      "intermediates": [],
      "product": "C=C(C)c1ccccc1",
      "product_label": "2-phenylpropene",
      "reaction_type": "olefination",
      "reversible": false,
      "committed_step_index": 1,
      "provenance": "professor-slide",
      "balance_lhs": [
        "CC(=O)c1ccccc1",
        "[CH2-][P+](c1ccccc1)(c1ccccc1)c1ccccc1"
      ],
      "balance_rhs": [
        "C=C(C)c1ccccc1",
        "O=P(c1ccccc1)(c1ccccc1)c1ccccc1"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "unavailable (classifier has no opinion (OtherReaction))"
        },
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/wittig-olefination-start-light.svg",
        "start_dark": "reactions/wittig-olefination-start-dark.svg",
        "product_light": "reactions/wittig-olefination-product-light.svg",
        "product_dark": "reactions/wittig-olefination-product-dark.svg"
      }
    },
    {
      "id": "imine-formation",
      "name": "Imine formation",
      "family": "carbonyls/imine-enamine",
      "tier": 1,
      "reactants": [
        "CC(=O)c1ccccc1"
      ],
      "reactant_labels": [
        "acetophenone"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "CN"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "",
            "acid_base": "acidic",
            "notes": "pH about 4 to 5. Too acidic and the amine is protonated into a non-nucleophile; too basic and dehydration never happens."
          },
          "byproducts": [
            "O"
          ]
        }
      ],
      "intermediates": [],
      "product": "C/N=C(\\C)c1ccccc1",
      "product_label": "N-methyl imine",
      "reaction_type": "condensation by addition-elimination",
      "reversible": true,
      "committed_step_index": 1,
      "provenance": "professor-slide",
      "balance_lhs": [
        "CC(=O)c1ccccc1",
        "CN"
      ],
      "balance_rhs": [
        "C/N=C(\\C)c1ccccc1",
        "O"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "agrees"
        },
        "classifier_label": "Addition of primary amines to ketones/thiocarbonyls",
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/imine-formation-start-light.svg",
        "start_dark": "reactions/imine-formation-start-dark.svg",
        "product_light": "reactions/imine-formation-product-light.svg",
        "product_dark": "reactions/imine-formation-product-dark.svg"
      }
    },
    {
      "id": "acetal-protection",
      "name": "Acetal protection",
      "family": "carbonyls/protecting-groups",
      "tier": 1,
      "reactants": [
        "CC(=O)c1ccccc1"
      ],
      "reactant_labels": [
        "acetophenone"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "OCCO"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "",
            "acid_base": "acidic",
            "notes": "Catalytic acid, water removed to drive it. Reversed by aqueous acid, which is what makes it a protecting group."
          },
          "byproducts": [
            "O"
          ]
        }
      ],
      "intermediates": [],
      "product": "CC1(c2ccccc2)OCCO1",
      "product_label": "cyclic acetal",
      "reaction_type": "protection",
      "reversible": true,
      "committed_step_index": null,
      "provenance": "professor-slide",
      "balance_lhs": [
        "CC(=O)c1ccccc1",
        "OCCO"
      ],
      "balance_rhs": [
        "CC1(c2ccccc2)OCCO1",
        "O"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "unavailable (classifier has no opinion (OtherReaction))"
        },
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/acetal-protection-start-light.svg",
        "start_dark": "reactions/acetal-protection-start-dark.svg",
        "product_light": "reactions/acetal-protection-product-light.svg",
        "product_dark": "reactions/acetal-protection-product-dark.svg"
      }
    },
    {
      "id": "nabh4-reduction",
      "name": "Sodium borohydride reduction",
      "family": "carbonyls/reduction",
      "tier": 2,
      "reactants": [
        "CC(=O)c1ccccc1"
      ],
      "reactant_labels": [
        "acetophenone"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "[BH4-]",
            "NaBH4"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "methanol",
            "acid_base": "basic",
            "notes": "Basic, nucleophilic hydride delivery. NOT acidic. A protic solvent is fine; acid is not, because borohydride is destroyed by acid before it reduces anything. Scope: aldehydes, ketones, epoxides, acid chlorides."
          },
          "byproducts": []
        },
        {
          "order": 2,
          "role": "workup",
          "reagents": [
            "[H3O+]"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "water",
            "acid_base": "acidic",
            "notes": "The acid appears only here. This is the stage that was wrongly labelled as the reaction's conditions."
          },
          "byproducts": []
        }
      ],
      "intermediates": [
        "CC([O-])c1ccccc1"
      ],
      "product": "CC(O)c1ccccc1",
      "product_label": "1-phenylethanol",
      "reaction_type": "reduction",
      "reversible": false,
      "committed_step_index": 1,
      "provenance": "professor-slide",
      "balance_lhs": [
        "CC(=O)c1ccccc1"
      ],
      "balance_rhs": [
        "CC(O)c1ccccc1"
      ],
      "redox": true,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "REDOX_OK",
          "classification": "agrees"
        },
        "classifier_label": "Reduction of ketone to secondary alcohol",
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/nabh4-reduction-start-light.svg",
        "start_dark": "reactions/nabh4-reduction-start-dark.svg",
        "product_light": "reactions/nabh4-reduction-product-light.svg",
        "product_dark": "reactions/nabh4-reduction-product-dark.svg"
      }
    },
    {
      "id": "lialh4-reduction",
      "name": "Lithium aluminium hydride reduction",
      "family": "carbonyls/reduction",
      "tier": 2,
      "reactants": [
        "COC(=O)c1ccccc1"
      ],
      "reactant_labels": [
        "methyl benzoate"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "[AlH4-]",
            "LiAlH4"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "THF",
            "acid_base": "basic",
            "notes": "Aprotic solvent only. Stronger than NaBH4: additionally reduces esters, anhydrides and amides. LiBH4 sits between the two, and like every borohydride is destroyed by acid."
          },
          "byproducts": [
            "CO"
          ]
        },
        {
          "order": 2,
          "role": "workup",
          "reagents": [
            "[H3O+]"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "water",
            "acid_base": "acidic",
            "notes": "Separate step. The reduction itself is not acidic."
          },
          "byproducts": []
        }
      ],
      "intermediates": [],
      "product": "OCc1ccccc1",
      "product_label": "benzyl alcohol",
      "reaction_type": "reduction",
      "reversible": false,
      "committed_step_index": 1,
      "provenance": "professor-slide",
      "balance_lhs": [
        "O=C(OC)c1ccccc1"
      ],
      "balance_rhs": [
        "OCc1ccccc1",
        "CO"
      ],
      "redox": true,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "REDOX_OK",
          "classification": "agrees"
        },
        "classifier_label": "Reduction of ester to primary alcohol",
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/lialh4-reduction-start-light.svg",
        "start_dark": "reactions/lialh4-reduction-start-dark.svg",
        "product_light": "reactions/lialh4-reduction-product-light.svg",
        "product_dark": "reactions/lialh4-reduction-product-dark.svg"
      }
    },
    {
      "id": "clemmensen",
      "name": "Clemmensen reduction",
      "family": "carbonyls/reduction",
      "tier": 2,
      "reactants": [
        "CC(=O)c1ccccc1"
      ],
      "reactant_labels": [
        "acetophenone"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "Zn(Hg)",
            "HCl"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "",
            "acid_base": "acidic",
            "notes": "Genuinely acidic, unlike a hydride reduction. Choose this when the molecule survives acid but not base."
          },
          "byproducts": [
            "O"
          ]
        }
      ],
      "intermediates": [],
      "product": "CCc1ccccc1",
      "product_label": "ethylbenzene",
      "reaction_type": "deoxygenation",
      "reversible": false,
      "committed_step_index": 1,
      "provenance": "professor-slide",
      "balance_lhs": [
        "CC(=O)c1ccccc1",
        "[H][H]",
        "[H][H]"
      ],
      "balance_rhs": [
        "CCc1ccccc1",
        "O"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "unavailable (classifier has no opinion (OtherReaction))"
        },
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/clemmensen-start-light.svg",
        "start_dark": "reactions/clemmensen-start-dark.svg",
        "product_light": "reactions/clemmensen-product-light.svg",
        "product_dark": "reactions/clemmensen-product-dark.svg"
      }
    },
    {
      "id": "wolff-kishner",
      "name": "Wolff-Kishner reduction",
      "family": "carbonyls/reduction",
      "tier": 2,
      "reactants": [
        "CC(=O)c1ccccc1"
      ],
      "reactant_labels": [
        "acetophenone"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "NN"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "",
            "acid_base": "neutral",
            "notes": "Hydrazone forms first."
          },
          "byproducts": [
            "O"
          ]
        },
        {
          "order": 2,
          "role": "reagent",
          "reagents": [
            "[OH-]",
            "KOH"
          ],
          "conditions": {
            "temperature_c": 200,
            "solvent": "",
            "acid_base": "basic",
            "notes": "Strongly basic and hot. The basic counterpart to Clemmensen: pick whichever the rest of the molecule tolerates."
          },
          "byproducts": [
            "N#N"
          ]
        }
      ],
      "intermediates": [
        "CC(=NN)c1ccccc1"
      ],
      "product": "CCc1ccccc1",
      "product_label": "ethylbenzene",
      "reaction_type": "deoxygenation",
      "reversible": false,
      "committed_step_index": 2,
      "provenance": "professor-slide",
      "balance_lhs": [
        "CC(=O)c1ccccc1",
        "NN"
      ],
      "balance_rhs": [
        "CCc1ccccc1",
        "N#N",
        "O"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "unavailable (classifier has no opinion (OtherReaction))"
        },
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/wolff-kishner-start-light.svg",
        "start_dark": "reactions/wolff-kishner-start-dark.svg",
        "product_light": "reactions/wolff-kishner-product-light.svg",
        "product_dark": "reactions/wolff-kishner-product-dark.svg"
      }
    },
    {
      "id": "jones-oxidation",
      "name": "Jones oxidation",
      "family": "alcohols-ethers/oxidation",
      "tier": 2,
      "reactants": [
        "OCc1ccccc1"
      ],
      "reactant_labels": [
        "benzyl alcohol"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "H2CrO4"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "water/acetone",
            "acid_base": "acidic",
            "notes": "Aqueous chromium goes all the way to the acid, because the aldehyde hydrate is what gets oxidised the second time. PCC in dry DCM stops at the aldehyde for exactly that reason."
          },
          "byproducts": []
        }
      ],
      "intermediates": [
        "O=Cc1ccccc1"
      ],
      "product": "O=C(O)c1ccccc1",
      "product_label": "benzoic acid",
      "reaction_type": "oxidation",
      "reversible": false,
      "committed_step_index": 1,
      "provenance": "professor-slide",
      "balance_lhs": [
        "OCc1ccccc1",
        "[O]"
      ],
      "balance_rhs": [
        "OC(=O)c1ccccc1"
      ],
      "redox": true,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "REDOX_OK",
          "classification": "agrees"
        },
        "classifier_label": "Oxidation of alcohol to carboxylic acid",
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/jones-oxidation-start-light.svg",
        "start_dark": "reactions/jones-oxidation-start-dark.svg",
        "product_light": "reactions/jones-oxidation-product-light.svg",
        "product_dark": "reactions/jones-oxidation-product-dark.svg"
      }
    },
    {
      "id": "socl2-acid-to-chloride",
      "name": "Carboxylic acid to acid chloride",
      "family": "derivatives/substitution",
      "tier": 1,
      "reactants": [
        "O=C(O)c1ccccc1"
      ],
      "reactant_labels": [
        "benzoic acid"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "O=S(Cl)Cl"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "",
            "acid_base": "neutral",
            "notes": "Pyridine optional. Byproducts are gases, so nothing needs separating."
          },
          "byproducts": [
            "O=S=O",
            "Cl"
          ]
        }
      ],
      "intermediates": [],
      "product": "O=C(Cl)c1ccccc1",
      "product_label": "benzoyl chloride",
      "reaction_type": "nucleophilic acyl substitution",
      "reversible": false,
      "committed_step_index": 1,
      "provenance": "professor-slide",
      "balance_lhs": [
        "OC(=O)c1ccccc1",
        "O=S(Cl)Cl"
      ],
      "balance_rhs": [
        "O=C(Cl)c1ccccc1",
        "O=S=O",
        "Cl"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "inconclusive"
        },
        "classifier_label": "Acyl chlorides from alcohols",
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/socl2-acid-to-chloride-start-light.svg",
        "start_dark": "reactions/socl2-acid-to-chloride-start-dark.svg",
        "product_light": "reactions/socl2-acid-to-chloride-product-light.svg",
        "product_dark": "reactions/socl2-acid-to-chloride-product-dark.svg"
      }
    },
    {
      "id": "fischer-esterification",
      "name": "Fischer esterification",
      "family": "derivatives/substitution",
      "tier": 1,
      "reactants": [
        "O=C(O)c1ccccc1",
        "CO"
      ],
      "reactant_labels": [
        "benzoic acid",
        "methanol"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "CO"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "",
            "acid_base": "acidic",
            "notes": "Every step reversible. Driven by excess alcohol or by removing water, not by the acid, which is only a catalyst."
          },
          "byproducts": [
            "O"
          ]
        }
      ],
      "intermediates": [],
      "product": "COC(=O)c1ccccc1",
      "product_label": "methyl benzoate",
      "reaction_type": "nucleophilic acyl substitution",
      "reversible": true,
      "committed_step_index": null,
      "provenance": "professor-slide",
      "balance_lhs": [
        "OC(=O)c1ccccc1",
        "CO"
      ],
      "balance_rhs": [
        "O=C(OC)c1ccccc1",
        "O"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "agrees"
        },
        "classifier_label": "Esterification of Carboxylic Acids",
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/fischer-esterification-start-light.svg",
        "start_dark": "reactions/fischer-esterification-start-dark.svg",
        "product_light": "reactions/fischer-esterification-product-light.svg",
        "product_dark": "reactions/fischer-esterification-product-dark.svg"
      }
    },
    {
      "id": "acidchloride-to-amide",
      "name": "Acid chloride to amide",
      "family": "derivatives/substitution",
      "tier": 1,
      "reactants": [
        "O=C(Cl)c1ccccc1",
        "CN"
      ],
      "reactant_labels": [
        "benzoyl chloride",
        "methylamine"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "CN"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "",
            "acid_base": "basic",
            "notes": "Downhill only on the reactivity ladder: acid chloride > anhydride > ester > amide. An amide will not go back up it."
          },
          "byproducts": [
            "Cl"
          ]
        }
      ],
      "intermediates": [],
      "product": "CNC(=O)c1ccccc1",
      "product_label": "N-methylbenzamide",
      "reaction_type": "nucleophilic acyl substitution",
      "reversible": false,
      "committed_step_index": 1,
      "provenance": "professor-slide",
      "balance_lhs": [
        "O=C(Cl)c1ccccc1",
        "CN"
      ],
      "balance_rhs": [
        "O=C(NC)c1ccccc1",
        "Cl"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "agrees"
        },
        "classifier_label": "Acylation of Nitrogen Nucleophiles by Acyl/Thioacyl/Carbamoyl Halides and Analogs_OS",
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/acidchloride-to-amide-start-light.svg",
        "start_dark": "reactions/acidchloride-to-amide-start-dark.svg",
        "product_light": "reactions/acidchloride-to-amide-product-light.svg",
        "product_dark": "reactions/acidchloride-to-amide-product-dark.svg"
      }
    },
    {
      "id": "ester-acidic-hydrolysis",
      "name": "Acidic ester hydrolysis",
      "family": "derivatives/hydrolysis",
      "tier": 1,
      "reactants": [
        "COC(=O)c1ccccc1",
        "O"
      ],
      "reactant_labels": [
        "methyl benzoate",
        "water"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "[H3O+]"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "water",
            "acid_base": "acidic",
            "notes": "Reversible, being Fischer esterification run backwards. NaOH instead gives the carboxylate and is effectively irreversible."
          },
          "byproducts": [
            "CO"
          ]
        }
      ],
      "intermediates": [],
      "product": "O=C(O)c1ccccc1",
      "product_label": "benzoic acid",
      "reaction_type": "nucleophilic acyl substitution",
      "reversible": true,
      "committed_step_index": null,
      "provenance": "professor-slide",
      "balance_lhs": [
        "O=C(OC)c1ccccc1",
        "O"
      ],
      "balance_rhs": [
        "OC(=O)c1ccccc1",
        "CO"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "agrees"
        },
        "classifier_label": "Ester saponification (methyl deprotection)",
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/ester-acidic-hydrolysis-start-light.svg",
        "start_dark": "reactions/ester-acidic-hydrolysis-start-dark.svg",
        "product_light": "reactions/ester-acidic-hydrolysis-product-light.svg",
        "product_dark": "reactions/ester-acidic-hydrolysis-product-dark.svg"
      }
    },
    {
      "id": "gilman-to-ketone",
      "name": "Gilman reagent to a ketone",
      "family": "derivatives/substitution",
      "tier": 2,
      "reactants": [
        "O=C(Cl)c1ccccc1"
      ],
      "reactant_labels": [
        "benzoyl chloride"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "[CH3-]",
            "(CH3)2CuLi"
          ],
          "conditions": {
            "temperature_c": -78,
            "solvent": "THF",
            "acid_base": "basic",
            "notes": "Acid chlorides only. The soft cuprate and the low temperature are what stop it adding twice to give the alcohol."
          },
          "byproducts": [
            "[Cl-]"
          ]
        },
        {
          "order": 2,
          "role": "workup",
          "reagents": [
            "[H3O+]"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "water",
            "acid_base": "acidic",
            "notes": "Workup for the other reagents present, not part of the substitution itself."
          },
          "byproducts": []
        }
      ],
      "intermediates": [],
      "product": "CC(=O)c1ccccc1",
      "product_label": "acetophenone",
      "reaction_type": "nucleophilic acyl substitution",
      "reversible": false,
      "committed_step_index": 1,
      "provenance": "professor-slide",
      "balance_lhs": [
        "O=C(Cl)c1ccccc1",
        "[CH3-]"
      ],
      "balance_rhs": [
        "CC(=O)c1ccccc1",
        "[Cl-]"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "unavailable (classifier has no opinion (OtherReaction))"
        },
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/gilman-to-ketone-start-light.svg",
        "start_dark": "reactions/gilman-to-ketone-start-dark.svg",
        "product_light": "reactions/gilman-to-ketone-product-light.svg",
        "product_dark": "reactions/gilman-to-ketone-product-dark.svg"
      }
    },
    {
      "id": "dibalh-to-aldehyde",
      "name": "DIBAL-H partial reduction of an ester",
      "family": "derivatives/reduction",
      "tier": 2,
      "reactants": [
        "COC(=O)c1ccccc1"
      ],
      "reactant_labels": [
        "methyl benzoate"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "DIBALH"
          ],
          "conditions": {
            "temperature_c": -78,
            "solvent": "toluene",
            "acid_base": "basic",
            "notes": "One hydride delivery. The tetrahedral alkoxide is stable at -78 C and does not collapse until workup, which is the whole reason this stops at the aldehyde."
          },
          "byproducts": [
            "CO"
          ]
        },
        {
          "order": 2,
          "role": "workup",
          "reagents": [
            "[H3O+]"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "water",
            "acid_base": "acidic",
            "notes": "Separate step. The reduction itself is not acidic."
          },
          "byproducts": []
        }
      ],
      "intermediates": [],
      "product": "O=Cc1ccccc1",
      "product_label": "benzaldehyde",
      "reaction_type": "reduction",
      "reversible": false,
      "committed_step_index": 1,
      "provenance": "professor-slide",
      "balance_lhs": [
        "O=C(OC)c1ccccc1"
      ],
      "balance_rhs": [
        "O=Cc1ccccc1",
        "CO"
      ],
      "redox": true,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "REDOX_OK",
          "classification": "unavailable (classifier has no opinion (OtherReaction))"
        },
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/dibalh-to-aldehyde-start-light.svg",
        "start_dark": "reactions/dibalh-to-aldehyde-start-dark.svg",
        "product_light": "reactions/dibalh-to-aldehyde-product-light.svg",
        "product_dark": "reactions/dibalh-to-aldehyde-product-dark.svg"
      }
    },
    {
      "id": "nitrile-formation",
      "name": "Amide dehydration to a nitrile",
      "family": "nitriles/formation",
      "tier": 2,
      "reactants": [
        "NC(=O)c1ccccc1"
      ],
      "reactant_labels": [
        "benzamide"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "O=S(Cl)Cl"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "",
            "acid_base": "neutral",
            "notes": "Primary amide only. Mechanism not tested per the board, so encode the transformation without requiring a drawing."
          },
          "byproducts": [
            "O=S=O",
            "Cl",
            "Cl"
          ]
        }
      ],
      "intermediates": [],
      "product": "N#Cc1ccccc1",
      "product_label": "benzonitrile",
      "reaction_type": "dehydration",
      "reversible": false,
      "committed_step_index": 1,
      "provenance": "professor-slide",
      "balance_lhs": [
        "O=C(N)c1ccccc1",
        "O=S(Cl)Cl"
      ],
      "balance_rhs": [
        "N#Cc1ccccc1",
        "O=S=O",
        "Cl",
        "Cl"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "unavailable (classifier has no opinion (OtherReaction))"
        },
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/nitrile-formation-start-light.svg",
        "start_dark": "reactions/nitrile-formation-start-dark.svg",
        "product_light": "reactions/nitrile-formation-product-light.svg",
        "product_dark": "reactions/nitrile-formation-product-dark.svg"
      }
    },
    {
      "id": "nitrile-basic-hydrolysis",
      "name": "Basic nitrile hydrolysis",
      "family": "nitriles/hydrolysis",
      "tier": 2,
      "reactants": [
        "N#Cc1ccccc1"
      ],
      "reactant_labels": [
        "benzonitrile"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "[OH-]",
            "NaOH"
          ],
          "conditions": {
            "temperature_c": 100,
            "solvent": "water",
            "acid_base": "basic",
            "notes": "Harsh. Goes through the amide and includes a tautomerisation. The steps before the committed hydration are reversible detours."
          },
          "byproducts": [
            "N"
          ]
        }
      ],
      "intermediates": [
        "NC(=O)c1ccccc1"
      ],
      "product": "O=C([O-])c1ccccc1",
      "product_label": "benzoate",
      "reaction_type": "hydrolysis",
      "reversible": false,
      "committed_step_index": 1,
      "provenance": "professor-slide",
      "balance_lhs": [
        "N#Cc1ccccc1",
        "O",
        "[OH-]"
      ],
      "balance_rhs": [
        "[O-]C(=O)c1ccccc1",
        "N"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "unavailable (classifier has no opinion (OtherReaction))"
        },
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/nitrile-basic-hydrolysis-start-light.svg",
        "start_dark": "reactions/nitrile-basic-hydrolysis-start-dark.svg",
        "product_light": "reactions/nitrile-basic-hydrolysis-product-light.svg",
        "product_dark": "reactions/nitrile-basic-hydrolysis-product-dark.svg"
      }
    },
    {
      "id": "nitrile-reduction",
      "name": "Nitrile reduction to a primary amine",
      "family": "nitriles/reduction",
      "tier": 2,
      "reactants": [
        "N#Cc1ccccc1"
      ],
      "reactant_labels": [
        "benzonitrile"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "[AlH4-]",
            "LiAlH4"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "THF",
            "acid_base": "basic",
            "notes": "Two hydride deliveries. Full mechanism is on the board, so this is a good drawing exercise."
          },
          "byproducts": []
        },
        {
          "order": 2,
          "role": "workup",
          "reagents": [
            "[H3O+]"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "water",
            "acid_base": "acidic",
            "notes": "Separate step. The reduction itself is not acidic."
          },
          "byproducts": []
        }
      ],
      "intermediates": [],
      "product": "NCc1ccccc1",
      "product_label": "benzylamine",
      "reaction_type": "reduction",
      "reversible": false,
      "committed_step_index": 1,
      "provenance": "professor-slide",
      "balance_lhs": [
        "N#Cc1ccccc1"
      ],
      "balance_rhs": [
        "NCc1ccccc1"
      ],
      "redox": true,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "REDOX_OK",
          "classification": "agrees"
        },
        "classifier_label": "Reduction of nitrile to amine",
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/nitrile-reduction-start-light.svg",
        "start_dark": "reactions/nitrile-reduction-start-dark.svg",
        "product_light": "reactions/nitrile-reduction-product-light.svg",
        "product_dark": "reactions/nitrile-reduction-product-dark.svg"
      }
    },
    {
      "id": "aldol-addition",
      "name": "Aldol addition",
      "family": "enolates/aldol",
      "tier": 3,
      "reactants": [
        "CC=O",
        "CC=O"
      ],
      "reactant_labels": [
        "acetaldehyde",
        "acetaldehyde"
      ],
      "stages": [
        {
          "order": 1,
          "role": "catalyst",
          "reagents": [
            "[OH-]",
            "NaOH"
          ],
          "conditions": {
            "temperature_c": 5,
            "solvent": "water",
            "acid_base": "basic",
            "notes": "Dilute base and cold. One molecule is deprotonated alpha to the carbonyl; that enolate attacks the carbonyl of another."
          },
          "byproducts": []
        }
      ],
      "intermediates": [
        "[CH2-]C=O"
      ],
      "product": "CC(O)CC=O",
      "product_label": "3-hydroxybutanal",
      "reaction_type": "aldol addition",
      "reversible": true,
      "committed_step_index": null,
      "provenance": "ai-proposed",
      "balance_lhs": [
        "CC=O",
        "CC=O"
      ],
      "balance_rhs": [
        "CC(O)CC=O"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "unavailable (classifier has no opinion (OtherReaction))"
        },
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/aldol-addition-start-light.svg",
        "start_dark": "reactions/aldol-addition-start-dark.svg",
        "product_light": "reactions/aldol-addition-product-light.svg",
        "product_dark": "reactions/aldol-addition-product-dark.svg"
      }
    },
    {
      "id": "aldol-condensation",
      "name": "Aldol condensation",
      "family": "enolates/aldol",
      "tier": 3,
      "reactants": [
        "CC=O",
        "CC=O"
      ],
      "reactant_labels": [
        "acetaldehyde",
        "acetaldehyde"
      ],
      "stages": [
        {
          "order": 1,
          "role": "catalyst",
          "reagents": [
            "[OH-]",
            "NaOH"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "water",
            "acid_base": "basic",
            "notes": "The aldol addition first."
          },
          "byproducts": []
        },
        {
          "order": 2,
          "role": "reagent",
          "reagents": [
            "[OH-]"
          ],
          "conditions": {
            "temperature_c": 80,
            "solvent": "",
            "acid_base": "basic",
            "notes": "Heat dehydrates the aldol. The alkene that forms is conjugated with the carbonyl, and that conjugation is what makes the loss of water worth it."
          },
          "byproducts": [
            "O"
          ]
        }
      ],
      "intermediates": [
        "CC(O)CC=O"
      ],
      "product": "CC=CC=O",
      "product_label": "but-2-enal",
      "reaction_type": "aldol condensation",
      "reversible": false,
      "committed_step_index": 2,
      "provenance": "ai-proposed",
      "balance_lhs": [
        "CC=O",
        "CC=O"
      ],
      "balance_rhs": [
        "CC=CC=O",
        "O"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "unavailable (classifier has no opinion (OtherReaction))"
        },
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/aldol-condensation-start-light.svg",
        "start_dark": "reactions/aldol-condensation-start-dark.svg",
        "product_light": "reactions/aldol-condensation-product-light.svg",
        "product_dark": "reactions/aldol-condensation-product-dark.svg"
      }
    },
    {
      "id": "claisen-condensation",
      "name": "Claisen condensation",
      "family": "enolates/claisen",
      "tier": 3,
      "reactants": [
        "CCOC(C)=O",
        "CCOC(C)=O"
      ],
      "reactant_labels": [
        "ethyl acetate",
        "ethyl acetate"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "CC[O-]",
            "NaOEt"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "ethanol",
            "acid_base": "basic",
            "notes": "The alkoxide must match the ester's alkoxy group, or transesterification scrambles the product into a mixture."
          },
          "byproducts": [
            "CCO"
          ]
        },
        {
          "order": 2,
          "role": "workup",
          "reagents": [
            "[H3O+]"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "water",
            "acid_base": "acidic",
            "notes": "The product is unusually acidic between the two carbonyls, so it sits deprotonated until this step."
          },
          "byproducts": []
        }
      ],
      "intermediates": [],
      "product": "CCOC(=O)CC(C)=O",
      "product_label": "ethyl acetoacetate",
      "reaction_type": "claisen condensation",
      "reversible": false,
      "committed_step_index": 1,
      "provenance": "ai-proposed",
      "balance_lhs": [
        "CCOC(C)=O",
        "CCOC(C)=O"
      ],
      "balance_rhs": [
        "CCOC(=O)CC(C)=O",
        "CCO"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "unavailable (classifier has no opinion (OtherReaction))"
        },
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/claisen-condensation-start-light.svg",
        "start_dark": "reactions/claisen-condensation-start-dark.svg",
        "product_light": "reactions/claisen-condensation-product-light.svg",
        "product_dark": "reactions/claisen-condensation-product-dark.svg"
      }
    },
    {
      "id": "michael-addition",
      "name": "Michael addition",
      "family": "enolates/michael",
      "tier": 3,
      "reactants": [
        "C=CC(C)=O",
        "CC(C)=O"
      ],
      "reactant_labels": [
        "but-3-en-2-one",
        "acetone"
      ],
      "stages": [
        {
          "order": 1,
          "role": "catalyst",
          "reagents": [
            "[OH-]"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "",
            "acid_base": "basic",
            "notes": "1,4 rather than 1,2 because a stabilised, soft enolate adds conjugately. A Grignard on the same substrate adds 1,2 instead."
          },
          "byproducts": []
        }
      ],
      "intermediates": [],
      "product": "CC(=O)CCCC(C)=O",
      "product_label": "heptane-2,6-dione",
      "reaction_type": "conjugate addition",
      "reversible": false,
      "committed_step_index": 1,
      "provenance": "ai-proposed",
      "balance_lhs": [
        "C=CC(C)=O",
        "CC(C)=O"
      ],
      "balance_rhs": [
        "CC(=O)CCCC(C)=O"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "agrees"
        },
        "classifier_label": "Michael addition methyl",
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/michael-addition-start-light.svg",
        "start_dark": "reactions/michael-addition-start-dark.svg",
        "product_light": "reactions/michael-addition-product-light.svg",
        "product_dark": "reactions/michael-addition-product-dark.svg"
      }
    },
    {
      "id": "alpha-halogenation",
      "name": "Alpha halogenation",
      "family": "enolates/halogenation",
      "tier": 3,
      "reactants": [
        "CC(=O)c1ccccc1"
      ],
      "reactant_labels": [
        "acetophenone"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "BrBr"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "acetic acid",
            "acid_base": "acidic",
            "notes": "Under acid the enol forms slowly and is the nucleophile, so monohalogenation is controllable. Under base the first halogenation makes the next one faster and it runs on to the trihalide."
          },
          "byproducts": [
            "Br"
          ]
        }
      ],
      "intermediates": [
        "C=C(O)c1ccccc1"
      ],
      "product": "O=C(CBr)c1ccccc1",
      "product_label": "phenacyl bromide",
      "reaction_type": "alpha halogenation",
      "reversible": false,
      "committed_step_index": 1,
      "provenance": "ai-proposed",
      "balance_lhs": [
        "CC(=O)c1ccccc1",
        "BrBr"
      ],
      "balance_rhs": [
        "BrCC(=O)c1ccccc1",
        "Br"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "inconclusive"
        },
        "classifier_label": "Bromination",
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/alpha-halogenation-start-light.svg",
        "start_dark": "reactions/alpha-halogenation-start-dark.svg",
        "product_light": "reactions/alpha-halogenation-product-light.svg",
        "product_dark": "reactions/alpha-halogenation-product-dark.svg"
      }
    },
    {
      "id": "malonic-ester-synthesis",
      "name": "Malonic ester synthesis",
      "family": "enolates/decarboxylation",
      "tier": 3,
      "reactants": [
        "CCOC(=O)CC(=O)OCC"
      ],
      "reactant_labels": [
        "diethyl malonate"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "CC[O-]",
            "NaOEt"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "ethanol",
            "acid_base": "basic",
            "notes": "The carbon between two esters is acidic enough for an alkoxide to deprotonate it completely."
          },
          "byproducts": [
            "CCO"
          ]
        },
        {
          "order": 2,
          "role": "reagent",
          "reagents": [
            "CI",
            "CH3I"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "",
            "acid_base": "neutral",
            "notes": "SN2, so a primary halide only. A tertiary one eliminates instead."
          },
          "byproducts": [
            "I"
          ]
        },
        {
          "order": 3,
          "role": "workup",
          "reagents": [
            "[H3O+]"
          ],
          "conditions": {
            "temperature_c": 100,
            "solvent": "water",
            "acid_base": "acidic",
            "notes": "Hydrolyses both esters, then heat drives off one carboxyl as CO2. The diacid decarboxylates readily because the second carbonyl can take the electrons."
          },
          "byproducts": [
            "CCO",
            "O=C=O"
          ]
        }
      ],
      "intermediates": [
        "CCOC(=O)C(C)C(=O)OCC"
      ],
      "product": "CCC(=O)O",
      "product_label": "propanoic acid",
      "reaction_type": "alkylation then decarboxylation",
      "reversible": false,
      "committed_step_index": 2,
      "provenance": "ai-proposed",
      "balance_lhs": [
        "CCOC(=O)CC(=O)OCC",
        "CI",
        "O",
        "O"
      ],
      "balance_rhs": [
        "CCC(=O)O",
        "O=C=O",
        "CCO",
        "CCO",
        "I"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "unavailable (classifier has no opinion (OtherReaction))"
        },
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/malonic-ester-synthesis-start-light.svg",
        "start_dark": "reactions/malonic-ester-synthesis-start-dark.svg",
        "product_light": "reactions/malonic-ester-synthesis-product-light.svg",
        "product_dark": "reactions/malonic-ester-synthesis-product-dark.svg"
      }
    },
    {
      "id": "robinson-annulation",
      "name": "Robinson annulation",
      "family": "enolates/annulation",
      "tier": 3,
      "reactants": [
        "O=C1CCCCC1",
        "C=CC(C)=O"
      ],
      "reactant_labels": [
        "cyclohexanone",
        "but-3-en-2-one"
      ],
      "stages": [
        {
          "order": 1,
          "role": "catalyst",
          "reagents": [
            "[OH-]"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "",
            "acid_base": "basic",
            "notes": "Michael addition first, making a 1,5-diketone."
          },
          "byproducts": []
        },
        {
          "order": 2,
          "role": "reagent",
          "reagents": [
            "[OH-]"
          ],
          "conditions": {
            "temperature_c": 80,
            "solvent": "",
            "acid_base": "basic",
            "notes": "Then an intramolecular aldol condensation closes the new six ring. Two named reactions in sequence, which is why it is worth learning as one."
          },
          "byproducts": [
            "O"
          ]
        }
      ],
      "intermediates": [
        "CC(=O)CCC1CCCCC1=O"
      ],
      "product": "O=C1C=C2CCCCC2CC1",
      "product_label": "bicyclic enone",
      "reaction_type": "annulation by conjugate addition then aldol condensation",
      "reversible": false,
      "committed_step_index": 2,
      "provenance": "ai-proposed",
      "balance_lhs": [
        "O=C1CCCCC1",
        "C=CC(C)=O"
      ],
      "balance_rhs": [
        "O=C1CCC2CCCCC2=C1",
        "O"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "unavailable (classifier has no opinion (OtherReaction))"
        },
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/robinson-annulation-start-light.svg",
        "start_dark": "reactions/robinson-annulation-start-dark.svg",
        "product_light": "reactions/robinson-annulation-product-light.svg",
        "product_dark": "reactions/robinson-annulation-product-dark.svg"
      }
    },
    {
      "id": "alcohol-to-halide",
      "name": "Alcohol to alkyl halide with HX",
      "family": "alcohols-ethers/substitution",
      "tier": 2,
      "reactants": [
        "CC(C)(C)O"
      ],
      "reactant_labels": [
        "tert-butanol"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "Br",
            "HBr"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "",
            "acid_base": "acidic",
            "notes": "Protonate first. OH is a terrible leaving group and water is a good one, and that swap is the whole chapter. Tertiary here, so SN1."
          },
          "byproducts": [
            "O"
          ]
        }
      ],
      "intermediates": [
        "CC(C)(C)[OH2+]"
      ],
      "product": "CC(C)(C)Br",
      "product_label": "2-bromo-2-methylpropane",
      "reaction_type": "nucleophilic substitution",
      "reversible": false,
      "committed_step_index": 1,
      "provenance": "ai-proposed",
      "balance_lhs": [
        "CC(C)(C)O",
        "Br"
      ],
      "balance_rhs": [
        "CC(C)(C)Br",
        "O"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "inconclusive"
        },
        "classifier_label": "Alkyl bromides from alcohols",
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/alcohol-to-halide-start-light.svg",
        "start_dark": "reactions/alcohol-to-halide-start-dark.svg",
        "product_light": "reactions/alcohol-to-halide-product-light.svg",
        "product_dark": "reactions/alcohol-to-halide-product-dark.svg"
      }
    },
    {
      "id": "alcohol-pbr3",
      "name": "Alcohol to alkyl halide with PBr3",
      "family": "alcohols-ethers/substitution",
      "tier": 2,
      "reactants": [
        "CCCCO"
      ],
      "reactant_labels": [
        "butan-1-ol"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "BrP(Br)Br",
            "PBr3"
          ],
          "conditions": {
            "temperature_c": 0,
            "solvent": "ether",
            "acid_base": "neutral",
            "notes": "PBr3 rather than HBr for a primary alcohol: no carbocation forms, so nothing rearranges. Three alcohols per PBr3."
          },
          "byproducts": [
            "OP(O)O"
          ]
        }
      ],
      "intermediates": [],
      "product": "CCCCBr",
      "product_label": "1-bromobutane",
      "reaction_type": "nucleophilic substitution",
      "reversible": false,
      "committed_step_index": 1,
      "provenance": "ai-proposed",
      "balance_lhs": [
        "CCCCO",
        "CCCCO",
        "CCCCO",
        "BrP(Br)Br"
      ],
      "balance_rhs": [
        "CCCCBr",
        "CCCCBr",
        "CCCCBr",
        "OP(O)O"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "inconclusive"
        },
        "classifier_label": "Alkyl bromides from alcohols",
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/alcohol-pbr3-start-light.svg",
        "start_dark": "reactions/alcohol-pbr3-start-dark.svg",
        "product_light": "reactions/alcohol-pbr3-product-light.svg",
        "product_dark": "reactions/alcohol-pbr3-product-dark.svg"
      }
    },
    {
      "id": "alcohol-dehydration",
      "name": "Acid-catalysed dehydration",
      "family": "alkenes/elimination",
      "tier": 2,
      "reactants": [
        "CC(C)(C)O"
      ],
      "reactant_labels": [
        "tert-butanol"
      ],
      "stages": [
        {
          "order": 1,
          "role": "catalyst",
          "reagents": [
            "OS(=O)(=O)O",
            "H2SO4"
          ],
          "conditions": {
            "temperature_c": 140,
            "solvent": "",
            "acid_base": "acidic",
            "notes": "E1 through the carbocation, so Zaitsev: the more substituted alkene wins. Heat drives the water off."
          },
          "byproducts": [
            "O"
          ]
        }
      ],
      "intermediates": [
        "CC(C)(C)[OH2+]"
      ],
      "product": "C=C(C)C",
      "product_label": "2-methylpropene",
      "reaction_type": "elimination",
      "reversible": true,
      "committed_step_index": 1,
      "provenance": "ai-proposed",
      "balance_lhs": [
        "CC(C)(C)O"
      ],
      "balance_rhs": [
        "CC(C)=C",
        "O"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "unavailable (classifier has no opinion (OtherReaction))"
        },
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/alcohol-dehydration-start-light.svg",
        "start_dark": "reactions/alcohol-dehydration-start-dark.svg",
        "product_light": "reactions/alcohol-dehydration-product-light.svg",
        "product_dark": "reactions/alcohol-dehydration-product-dark.svg"
      }
    },
    {
      "id": "pcc-oxidation",
      "name": "PCC oxidation to an aldehyde",
      "family": "alcohols-ethers/oxidation",
      "tier": 2,
      "reactants": [
        "CCCCO"
      ],
      "reactant_labels": [
        "butan-1-ol"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "PCC"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "dichloromethane",
            "acid_base": "neutral",
            "notes": "Anhydrous, which is the entire point. With no water there is no aldehyde hydrate, and with no hydrate there is nothing to oxidise a second time. Jones is aqueous and runs on to the acid."
          },
          "byproducts": []
        }
      ],
      "intermediates": [],
      "product": "CCCC=O",
      "product_label": "butanal",
      "reaction_type": "oxidation",
      "reversible": false,
      "committed_step_index": 1,
      "provenance": "ai-proposed",
      "balance_lhs": [
        "CCCCO"
      ],
      "balance_rhs": [
        "CCCC=O"
      ],
      "redox": true,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "REDOX_OK",
          "classification": "agrees"
        },
        "classifier_label": "Oxidation or Dehydrogenation of Alcohols to Aldehydes and Ketones",
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/pcc-oxidation-start-light.svg",
        "start_dark": "reactions/pcc-oxidation-start-dark.svg",
        "product_light": "reactions/pcc-oxidation-product-light.svg",
        "product_dark": "reactions/pcc-oxidation-product-dark.svg"
      }
    },
    {
      "id": "ether-cleavage",
      "name": "Acid-catalysed ether cleavage",
      "family": "alcohols-ethers/substitution",
      "tier": 2,
      "reactants": [
        "CCOC(C)(C)C"
      ],
      "reactant_labels": [
        "ethyl tert-butyl ether"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "Br",
            "HBr"
          ],
          "conditions": {
            "temperature_c": 100,
            "solvent": "",
            "acid_base": "acidic",
            "notes": "The halide attacks whichever carbon better supports positive charge. Tertiary here, so the tert-butyl side becomes the halide and the ethyl side leaves as the alcohol."
          },
          "byproducts": []
        }
      ],
      "intermediates": [],
      "product": "CCO",
      "product_label": "ethanol (with 2-bromo-2-methylpropane)",
      "reaction_type": "nucleophilic substitution",
      "reversible": false,
      "committed_step_index": 1,
      "provenance": "ai-proposed",
      "balance_lhs": [
        "CCOC(C)(C)C",
        "Br"
      ],
      "balance_rhs": [
        "CCO",
        "CC(C)(C)Br"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "inconclusive"
        },
        "classifier_label": "Ether cleavage to primary alcohol",
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/ether-cleavage-start-light.svg",
        "start_dark": "reactions/ether-cleavage-start-dark.svg",
        "product_light": "reactions/ether-cleavage-product-light.svg",
        "product_dark": "reactions/ether-cleavage-product-dark.svg"
      }
    },
    {
      "id": "epoxidation-mcpba",
      "name": "Epoxidation with mCPBA",
      "family": "alkenes/epoxidation",
      "tier": 2,
      "reactants": [
        "CC=CC"
      ],
      "reactant_labels": [
        "but-2-ene"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "OOC(=O)c1cccc(Cl)c1",
            "mCPBA"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "dichloromethane",
            "acid_base": "neutral",
            "notes": "One concerted oxygen delivery, so the alkene geometry is carried straight into the epoxide. cis stays cis."
          },
          "byproducts": [
            "OC(=O)c1cccc(Cl)c1"
          ]
        }
      ],
      "intermediates": [],
      "product": "CC1OC1C",
      "product_label": "2,3-dimethyloxirane",
      "reaction_type": "epoxidation",
      "reversible": false,
      "committed_step_index": 1,
      "provenance": "ai-proposed",
      "balance_lhs": [
        "CC=CC",
        "OOC(=O)c1cccc(Cl)c1"
      ],
      "balance_rhs": [
        "CC1OC1C",
        "OC(=O)c1cccc(Cl)c1"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "unavailable (classifier has no opinion (OtherReaction))"
        },
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/epoxidation-mcpba-start-light.svg",
        "start_dark": "reactions/epoxidation-mcpba-start-dark.svg",
        "product_light": "reactions/epoxidation-mcpba-product-light.svg",
        "product_dark": "reactions/epoxidation-mcpba-product-dark.svg"
      }
    },
    {
      "id": "epoxide-opening-base",
      "name": "Epoxide opening under base",
      "family": "alkenes/epoxide-opening",
      "tier": 2,
      "reactants": [
        "CC1(C)CO1"
      ],
      "reactant_labels": [
        "2,2-dimethyloxirane"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "C[O-]",
            "NaOMe"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "methanol",
            "acid_base": "basic",
            "notes": "Basic conditions: the nucleophile hits the LESS hindered carbon, because this is a plain SN2 and sterics decide. Acid flips it, since the protonated epoxide has carbocation character at the more substituted side."
          },
          "byproducts": []
        },
        {
          "order": 2,
          "role": "workup",
          "reagents": [
            "[H3O+]"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "water",
            "acid_base": "acidic",
            "notes": "Separate step. The reduction itself is not acidic."
          },
          "byproducts": []
        }
      ],
      "intermediates": [],
      "product": "COCC(C)(C)O",
      "product_label": "1-methoxy-2-methylpropan-2-ol",
      "reaction_type": "nucleophilic substitution",
      "reversible": false,
      "committed_step_index": 1,
      "provenance": "ai-proposed",
      "balance_lhs": [
        "CC1(C)OC1",
        "CO"
      ],
      "balance_rhs": [
        "CC(C)(O)COC"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "unavailable (classifier has no opinion (OtherReaction))"
        },
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/epoxide-opening-base-start-light.svg",
        "start_dark": "reactions/epoxide-opening-base-start-dark.svg",
        "product_light": "reactions/epoxide-opening-base-product-light.svg",
        "product_dark": "reactions/epoxide-opening-base-product-dark.svg"
      }
    },
    {
      "id": "nbs-allylic",
      "name": "Allylic bromination with NBS",
      "family": "alkenes/substitution",
      "tier": 2,
      "reactants": [
        "C=CCC"
      ],
      "reactant_labels": [
        "but-1-ene"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "BrN1C(=O)CCC1=O",
            "NBS"
          ],
          "conditions": {
            "temperature_c": 80,
            "solvent": "carbon tetrachloride",
            "acid_base": "neutral",
            "notes": "NBS rather than Br2 because it holds the bromine concentration very low, which favours the radical allylic substitution over ionic addition across the double bond."
          },
          "byproducts": [
            "O=C1CCC(=O)N1"
          ]
        }
      ],
      "intermediates": [],
      "product": "C=CC(C)Br",
      "product_label": "3-bromobut-1-ene",
      "reaction_type": "radical substitution",
      "reversible": false,
      "committed_step_index": 1,
      "provenance": "ai-proposed",
      "balance_lhs": [
        "C=CCC",
        "BrN1C(=O)CCC1=O"
      ],
      "balance_rhs": [
        "C=CC(Br)C",
        "O=C1CCC(=O)N1"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "inconclusive"
        },
        "classifier_label": "Bromination",
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/nbs-allylic-start-light.svg",
        "start_dark": "reactions/nbs-allylic-start-dark.svg",
        "product_light": "reactions/nbs-allylic-product-light.svg",
        "product_dark": "reactions/nbs-allylic-product-dark.svg"
      }
    },
    {
      "id": "diene-1-4-addition",
      "name": "1,4-addition to a conjugated diene",
      "family": "dienes/conjugate-addition",
      "tier": 2,
      "reactants": [
        "C=CC=C"
      ],
      "reactant_labels": [
        "buta-1,3-diene"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "Br",
            "HBr"
          ],
          "conditions": {
            "temperature_c": 40,
            "solvent": "",
            "acid_base": "acidic",
            "notes": "One equivalent. Cold traps the 1,2 product because it forms fastest; warm lets it revert and settle on the more substituted 1,4 alkene. Temperature is the variable being examined, not the reagent."
          },
          "byproducts": []
        }
      ],
      "intermediates": [
        "C=C[CH+]C"
      ],
      "product": "CC=CCBr",
      "product_label": "1-bromobut-2-ene",
      "reaction_type": "electrophilic addition",
      "reversible": true,
      "committed_step_index": 1,
      "provenance": "ai-proposed",
      "balance_lhs": [
        "C=CC=C",
        "Br"
      ],
      "balance_rhs": [
        "CC=CCBr"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "unavailable (classifier has no opinion (OtherReaction))"
        },
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/diene-1-4-addition-start-light.svg",
        "start_dark": "reactions/diene-1-4-addition-start-dark.svg",
        "product_light": "reactions/diene-1-4-addition-product-light.svg",
        "product_dark": "reactions/diene-1-4-addition-product-dark.svg"
      }
    },
    {
      "id": "diels-alder",
      "name": "Diels-Alder cycloaddition",
      "family": "dienes/diels-alder",
      "tier": 2,
      "reactants": [
        "C=CC=C",
        "C=CC=O"
      ],
      "reactant_labels": [
        "buta-1,3-diene",
        "acrolein"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "C=CC=O"
          ],
          "conditions": {
            "temperature_c": 100,
            "solvent": "",
            "acid_base": "neutral",
            "notes": "One concerted step, no intermediate. The electron-withdrawing group lowers the dienophile LUMO toward the diene HOMO, which is why a plain alkene is a poor dienophile. The diene must reach s-cis or nothing happens at all."
          },
          "byproducts": []
        }
      ],
      "intermediates": [],
      "product": "O=CC1CC=CCC1",
      "product_label": "cyclohex-3-ene-1-carbaldehyde",
      "reaction_type": "cycloaddition",
      "reversible": true,
      "committed_step_index": 1,
      "provenance": "ai-proposed",
      "balance_lhs": [
        "C=CC=C",
        "C=CC=O"
      ],
      "balance_rhs": [
        "O=CC1CCC=CC1"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "agrees"
        },
        "classifier_label": "Diels-Alder",
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/diels-alder-start-light.svg",
        "start_dark": "reactions/diels-alder-start-dark.svg",
        "product_light": "reactions/diels-alder-product-light.svg",
        "product_dark": "reactions/diels-alder-product-dark.svg"
      }
    },
    {
      "id": "eas-bromination",
      "name": "Electrophilic aromatic bromination",
      "family": "aromaticity/eas",
      "tier": 2,
      "reactants": [
        "c1ccccc1"
      ],
      "reactant_labels": [
        "benzene"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "BrBr",
            "FeBr3"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "",
            "acid_base": "neutral",
            "notes": "Substitution, not addition: getting the aromatic sextet back is worth more than the second new sigma bond addition would give. FeBr3 is there to make Br2 electrophilic enough."
          },
          "byproducts": [
            "Br"
          ]
        }
      ],
      "intermediates": [
        "Br[C+]1C=CC=CC1"
      ],
      "product": "Brc1ccccc1",
      "product_label": "bromobenzene",
      "reaction_type": "electrophilic aromatic substitution",
      "reversible": false,
      "committed_step_index": 1,
      "provenance": "ai-proposed",
      "balance_lhs": [
        "c1ccccc1",
        "BrBr"
      ],
      "balance_rhs": [
        "Brc1ccccc1",
        "Br"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "inconclusive"
        },
        "classifier_label": "Aromatic bromination",
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/eas-bromination-start-light.svg",
        "start_dark": "reactions/eas-bromination-start-dark.svg",
        "product_light": "reactions/eas-bromination-product-light.svg",
        "product_dark": "reactions/eas-bromination-product-dark.svg"
      }
    },
    {
      "id": "friedel-crafts-acylation",
      "name": "Friedel-Crafts acylation",
      "family": "aromaticity/eas",
      "tier": 2,
      "reactants": [
        "c1ccccc1"
      ],
      "reactant_labels": [
        "benzene"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "CC(=O)Cl",
            "AlCl3"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "",
            "acid_base": "neutral",
            "notes": "Acylation rather than alkylation when you want exactly one substituent: the acylium ion cannot rearrange, and the ketone product is deactivated so it does not react again."
          },
          "byproducts": [
            "Cl"
          ]
        }
      ],
      "intermediates": [
        "C[C+]=O"
      ],
      "product": "CC(=O)c1ccccc1",
      "product_label": "acetophenone",
      "reaction_type": "electrophilic aromatic substitution",
      "reversible": false,
      "committed_step_index": 1,
      "provenance": "ai-proposed",
      "balance_lhs": [
        "c1ccccc1",
        "CC(=O)Cl"
      ],
      "balance_rhs": [
        "CC(=O)c1ccccc1",
        "Cl"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "agrees"
        },
        "classifier_label": "Friedel-Crafts acylation",
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/friedel-crafts-acylation-start-light.svg",
        "start_dark": "reactions/friedel-crafts-acylation-start-dark.svg",
        "product_light": "reactions/friedel-crafts-acylation-product-light.svg",
        "product_dark": "reactions/friedel-crafts-acylation-product-dark.svg"
      }
    },
    {
      "id": "nitration",
      "name": "Nitration",
      "family": "aromaticity/eas",
      "tier": 2,
      "reactants": [
        "c1ccccc1"
      ],
      "reactant_labels": [
        "benzene"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "O[N+](=O)[O-]",
            "HNO3"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "",
            "acid_base": "acidic",
            "notes": "H2SO4 is not the solvent, it is there to make the nitronium ion. Without it HNO3 is not electrophilic enough."
          },
          "byproducts": [
            "O"
          ]
        }
      ],
      "intermediates": [
        "O=[N+]=O"
      ],
      "product": "O=[N+]([O-])c1ccccc1",
      "product_label": "nitrobenzene",
      "reaction_type": "electrophilic aromatic substitution",
      "reversible": false,
      "committed_step_index": 1,
      "provenance": "ai-proposed",
      "balance_lhs": [
        "c1ccccc1",
        "O[N+](=O)[O-]"
      ],
      "balance_rhs": [
        "O=[N+]([O-])c1ccccc1",
        "O"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "inconclusive"
        },
        "classifier_label": "Aromatic nitration with HNO3",
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/nitration-start-light.svg",
        "start_dark": "reactions/nitration-start-dark.svg",
        "product_light": "reactions/nitration-product-light.svg",
        "product_dark": "reactions/nitration-product-dark.svg"
      }
    },
    {
      "id": "diazonium-formation",
      "name": "Diazonium salt formation",
      "family": "amines/diazonium",
      "tier": 3,
      "reactants": [
        "Nc1ccccc1"
      ],
      "reactant_labels": [
        "aniline"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "ON=O",
            "NaNO2",
            "HCl"
          ],
          "conditions": {
            "temperature_c": 0,
            "solvent": "water",
            "acid_base": "acidic",
            "notes": "Zero to five degrees, and that is not a suggestion. Above about 5 C the salt decomposes. It is a handle rather than a destination: Sandmeyer and Schiemann both replace it with something else."
          },
          "byproducts": [
            "O",
            "O"
          ]
        }
      ],
      "intermediates": [],
      "product": "N#[N+]c1ccccc1",
      "product_label": "benzenediazonium ion",
      "reaction_type": "diazotisation",
      "reversible": false,
      "committed_step_index": 1,
      "provenance": "ai-proposed",
      "balance_lhs": [
        "Nc1ccccc1",
        "ON=O",
        "Cl"
      ],
      "balance_rhs": [
        "[N+](#N)c1ccccc1",
        "O",
        "O",
        "[Cl-]"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "unavailable (classifier has no opinion (OtherReaction))"
        },
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/diazonium-formation-start-light.svg",
        "start_dark": "reactions/diazonium-formation-start-dark.svg",
        "product_light": "reactions/diazonium-formation-product-light.svg",
        "product_dark": "reactions/diazonium-formation-product-dark.svg"
      }
    },
    {
      "id": "sandmeyer",
      "name": "Sandmeyer reaction",
      "family": "amines/substitution",
      "tier": 3,
      "reactants": [
        "N#[N+]c1ccccc1"
      ],
      "reactant_labels": [
        "benzenediazonium ion"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "[Br-]",
            "CuBr"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "",
            "acid_base": "neutral",
            "notes": "Nitrogen gas leaving is what makes this irreversible, and it is the best leaving group in the course. This is how you put a halide somewhere EAS would not have directed it."
          },
          "byproducts": [
            "N#N"
          ]
        }
      ],
      "intermediates": [],
      "product": "Brc1ccccc1",
      "product_label": "bromobenzene",
      "reaction_type": "nucleophilic substitution",
      "reversible": false,
      "committed_step_index": 1,
      "provenance": "ai-proposed",
      "balance_lhs": [
        "[N+](#N)c1ccccc1",
        "[Br-]"
      ],
      "balance_rhs": [
        "Brc1ccccc1",
        "N#N"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "unavailable (classifier has no opinion (OtherReaction))"
        },
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/sandmeyer-start-light.svg",
        "start_dark": "reactions/sandmeyer-start-dark.svg",
        "product_light": "reactions/sandmeyer-product-light.svg",
        "product_dark": "reactions/sandmeyer-product-dark.svg"
      }
    },
    {
      "id": "periodic-cleavage",
      "name": "Periodic acid cleavage",
      "family": "carbohydrates/oxidation",
      "tier": 3,
      "reactants": [
        "OCCO"
      ],
      "reactant_labels": [
        "ethane-1,2-diol"
      ],
      "stages": [
        {
          "order": 1,
          "role": "reagent",
          "reagents": [
            "O[I](=O)(=O)=O",
            "HIO4"
          ],
          "conditions": {
            "temperature_c": null,
            "solvent": "water",
            "acid_base": "neutral",
            "notes": "Cleaves the bond between two carbons that each carry an OH. Counting the fragments is how the ring size and substitution of a sugar gets worked out."
          },
          "byproducts": [
            "O[I](=O)=O",
            "O"
          ]
        }
      ],
      "intermediates": [],
      "product": "C=O",
      "product_label": "formaldehyde (two equivalents)",
      "reaction_type": "oxidative cleavage",
      "reversible": false,
      "committed_step_index": 1,
      "provenance": "ai-proposed",
      "balance_lhs": [
        "OCCO",
        "O[I](=O)(=O)=O"
      ],
      "balance_rhs": [
        "C=O",
        "C=O",
        "O[I](=O)=O",
        "O"
      ],
      "redox": false,
      "validation": {
        "checks": {
          "parse": "ok",
          "conservation": "BALANCED",
          "classification": "unavailable (classifier has no opinion (OtherReaction))"
        },
        "status": "ok",
        "problems": []
      },
      "art": {
        "start_light": "reactions/periodic-cleavage-start-light.svg",
        "start_dark": "reactions/periodic-cleavage-start-dark.svg",
        "product_light": "reactions/periodic-cleavage-product-light.svg",
        "product_dark": "reactions/periodic-cleavage-product-dark.svg"
      }
    }
  ]
};

export const REACTIONS = DATA.reactions;

/** Section 8: a class convention, not a law of nature. Instructor-configurable. */
export const PKA_LEAVING_GROUP_CUTOFF = DATA.pkaLeavingGroupCutoff;

export const byFamily = (family: string) =>
  REACTIONS.filter((r) => r.family === family);
export const byTier = (tier: number) => REACTIONS.filter((r) => r.tier === tier);
